### PR TITLE
Fixed whitespace in Settings & Edit Page #1198

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #1198

### CODE REVIEW

**Comment by wpsmort** [comment]
This is on hold until #1892 has been merged.  Once that PR has been merged, this PR will need to be checked for merge conflicts and tested.

**Comment by arnaudbroes** [comment]
@EkoJR the "Help" glyphicon and anchor text are no longer properly aligned in Chrome, Firefox and IE11 on Windows.

**Comment by EkoJR** [comment]
@arnaudbroes looks like that was introduced in #2133

I had to rebase the branch to try and better track the commit changes that occured. So, I'll have a new PR shortly.

**Comment by EkoJR** [comment]
Rebased to #2260

**Pull request closed without merging**
