### PR TITLE
Change naming and remove redundant arguments exclude_tax_terms filter

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #746

## Proposed changes

Changes name of an existing filter and removes unnecessary arguments.

## Types of changes

- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

Use to code example here to test this filter - https://semperplugins.com/wp-admin/post.php?post=4958&action=edit&lang=en. 

If the filter works, please also review the documentation and publish it.

### CODE REVIEW

**Comment by wpsmort** [comment]
As discussed, I've assigned this back to remove an extra line of code.

**Comment by arnaudbroes** [comment]
@wpsmort turns out I didn't have to. Confused it with another PR.

**Comment by wpsmort** [comment]
@arnaudbroes I'm getting these two errors when testing this PR.

The warning below is in reference to the line `array_push( $args['exclude'], '16' );` in the function (16 is the ID of my category)"

`PHP Warning:  array_push() expects parameter 1 to be array, null given in functions.php on line 351`

The notice below is in reference to the line `$excluded_terms = $args['exclude'];` in the function:

`PHP Notice:  Undefined index: exclude in functions.php on line 348`

**Comment by arnaudbroes** [comment]
@wpsmort this was happening because of a bug in the original filter where $args['exclude'] wouldn't be instantiated when no terms are excluded in the XML Sitemap menu. I've moved it a few lines up to fix it. Good catch! Please test the filter again with the code example in the documentation.

**Comment by wpsmort** [comment]
This is tested and is good.  I have published the doc here - https://semperplugins.com/documentation/aioseop-sitemap-exclude-tax-terms/

**Comment by EkoJR** [comment]
@arnaudbroes is going to double check his records to see if anyone may have used the old filter name for excluding terms. Although it wasn't documented, there may be a chance the filter is being used by those who came across it; who are knowledgeable in coding.

**Comment by arnaudbroes** [comment]
@EkoJR no one is using it yet so I'm sending it back to you for final approval.

**Pull request merged**
