### PR TITLE
Change Help Text Dropdown to Tooltips #1156

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #1156

### CODE REVIEW

**Comment by wpsmort** [comment]
@EkoJR I have tested this and found some problems where not all of the help text is showing.  Here are those instances where the complete help text doesn't show:

General Settings > Title Settings > Page Title Format
General Settings > Title Settings > Post Title Format
XML Sitemap > Additional Pages > Page URL
XML Sitemap > Priorities > Taxonomies (incorrect help text)
XML Sitemap > Priorities > Archive Pages (missing help text)
XML Sitemap > Priorities > Author Pages (missing help text)
XML Sitemap > Frequencies > Taxonomies (incorrect help text)
XML Sitemap > Frequencies > Archive Pages (missing help text)
XML Sitemap > Frequencies > Author Pages (missing help text)

**Comment by EkoJR** [comment]
I made the corrections, but I didn't see any problems with...

General Settings > Title Settings > Page Title Format
General Settings > Title Settings > Post Title Format

Initially I had confused 'General Settings > Title Settings > Home Page Title Format', and thought there was a problem as well, but both seem correct. Seems you may have had the same confusion as well.

**Comment by wpsmort** [comment]
@EkoJR The help text that is missing from Page Title Format is "This controls the format of the title tag for Pages.".

The help text that is missing from Post Title Format is "This controls the format of the title tag for Posts."

screen shot 2018-08-15 at 11 50 04 am

**Comment by EkoJR** [comment]
@wpsmort I thought it was the % items, but it was the CPT's title format was overwriting page & post. It should be fixed now.

**Comment by wpsmort** [comment]
@EkoJR As discussed, can you add back the links to the documentation so they are displayed in the tooltip like this:

screen shot 2018-08-16 at 2 27 51 pm

**Comment by EkoJR** [comment]
Restored the initial documentation links.

I noticed there were some links missing, or were duplicates. So, in a developer point of view, I tried to make it easier to analyze & manage documentation links in the future.

**Comment by wpsmort** [comment]
@EkoJR I checked the help text and it looks good with the links to the documentation.  I did find two problems with the help text as follows:

1.  Google Settings > Specify A Preferred Name - The help text reads DEV: Missing Help Text: aiosp_google_specify_site_name.  You can copy the help text from the Set Preferred Site Name field

2.  Custom Post Type Settings > Product Title Format - The help text is missing some of the macros.  This happens with any custom post type.  See screenshot:

screen shot 2018-08-17 at 12 24 20 pm

**Comment by wpsmort** [comment]
@EkoJR The latest commit removed text at the top of the help for the Title Format fields under Custom Post Type Settings.  The text should read "The following macros are supported:".  Please dd that text back.

screen shot 2018-08-20 at 11 50 17 am

**Comment by EkoJR** [comment]
Opps, sorry about that. I forgot to add that back in when changing how additional custom fields were being added.

**Comment by wpsmort** [comment]
@arnaudbroes Can you test this on all browsers on Windows.  Please test the following works:

1).  When you hover over a help icon the tooltip appears and stays visible until you mouse away
2).  When the tooltip is visible you can select text from inside the tooltip and copy it
3).  When the tooltip is visible you can click on the documentation link inside the tooltip
4).  There are no usability issues or browser console errors

Let me know if you have any questions or need help.

**Comment by arnaudbroes** [comment]
@wpsmort no issues in Google Chrome, Opera, Microsoft Edge and Mozilla Firefox.
In Microsoft Internet Explorer 11, however, HTML doesn't seem to be supported for tooltips.

**Comment by wpsmort** [comment]
@EkoJR Is there anything you can do here to support IE11 users? See @arnaudbroes comment and screenshot above.

**Comment by EkoJR** [comment]
@wpsmort I haven't been able to find a solution for IE11 users. I've also tried looking around a couple times and both Microsoft and jQuery devs don't provide any sort of solution.

**Comment by EkoJR** [comment]
@wpsmort Disregard the last comment. I found a syntax issue with IE, it should render as expected now.

**Comment by arnaudbroes** [comment]
@wpsmort @EkoJR I confirm that the tooltips are now fixed in IE11.
@michaeltorbert needs code review.

**Comment by michaeltorbert** [comment]
@EkoJR Please resolve the merge conflicts

**Comment by EkoJR** [comment]
Resolved merge conflicts on #1892

**Pull request closed without merging**
