### PR TITLE
Remove option "SEO for Content Types"

### PR DESCRIPTION
**Pull request by contactashish13**
#2028 and #2029

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 I tested this and found two problems as follows:

1.  The checkboxes for custom post types are not being output in these settings:
 - Display Settings > Show Columns Labels 
 - Google Settings > Display Google Authorship
 - Noindex Settings > Default to NOINDEX
 - Noindex Settings > Default to NOFOLLOW

See screenshot below:

screen shot 2018-11-12 at 2 27 24 pm

2. The title format for custom post types are coming from the Post Type Format field and not the Title Format field under Content Type Settings.  

To reproduce this, enter the format %post_title% - POST | %blog_title% in the Post Title Format field and then enter the format %post_title% - MEDIA | %blog_title% in the Media Title Format field.  View the source code of any media attachment page and you'll see that the title tag format is coming from the Post Type Format field and not the Media Title Format field.

**Comment by wpsmort** [comment]
@contactashish13 I have tested your latest commit and both bugs I reported above are still present.  Issue 1 does not exist in the master branch, it only exists in this PR.  I've set up a test site and sent you the login on Slack so you can see what I'm seeing.

**Comment by contactashish13** [comment]
@wpsmort once I reset all the settings I was able to reproduce both issues at my end and have fixed them in the latest commit. I have also applied my changes to the cloudways instance and tested successfully.

**Comment by wpsmort** [comment]
This is tested and is good. I've tested every combination of options and tested updating from v2.8 and v2.9.1 to make sure nothing breaks. This is ready for code review.

**Pull request merged**
