### PR TITLE
Remove spaces before and after anchor text #2243

### PR DESCRIPTION
**Pull request by onetarek**
## Fix the simple issue #2243

### CODE REVIEW

**Comment by EkoJR** [comment]
@michaeltorbert Should this be included in the 3.0 branch though?

**Comment by michaeltorbert** [comment]
> @michaeltorbert Should this be included in the 3.0 branch though?

@EkoJR  Why not?

**Comment by EkoJR** [comment]
@michaeltorbert Why not in the master branch? Didn't seem like a hotfix, and figured it would go well with the 3.0 updates.

**Comment by EkoJR** [comment]
Rebased and grunted #2270

**Pull request closed without merging**
