### PR TITLE
Improved display of date picker in Safari

### PR DESCRIPTION
**Pull request by wpsmort**
Issue #2739

## Proposed changes
The jQuery UI date picker doesn't look good in Safari so this adds CSS to improve the look.

## Types of changes
- Improves existing functionality
- Improves existing code

## Checklist
- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions
- Go to All in One SEO > XML Sitemap > Additional Pages and check the styling of the date picker in the Last Modified option
- Verify the styling in all modern browsers (specifically IE and Safari)
- Perform the same tests with the XML Sitemap and Video Sitemap in Pro

## Further comments
I've tested this in mobile Safari and it does not affect the look or behavior of the date field.  You should verify this does not affect mobile browsers on Android devices.

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@wpsmort 

Microsoft Edge:

image

Mozilla Firefox:

image

Internet Explorer:

image

Google Chrome:

image

@wpsmort all look good except for Google Chrome, but that seems to be pre-existing. Does it look the same in Chrome on MacOS, and if so, could we improve that too?

**Comment by arnaudbroes** [comment]
For Chrome I'm specifically referring to the lack of a border of the right side of the box and that there's two action buttons in the date field; one to manually increase or decrease the number; the other to open the datepicker.

**Comment by wpsmort** [comment]
@arnaudbroes It looks fine in Chrome on Mac (the right border is present):

Screen Shot 2019-09-03 at 12 00 43 PM

Can you tell why the border is missing in Chrome on Windows?

**Comment by wpsmort** [comment]
I discussed this with Arnaud and it turns out that the problem with the right border missing in Chrome on Windows was due to a browser plugin and did not happen if he tested in Incognito mode.

Testing is therefore good in all browsers.

**Pull request merged**
