### PR TITLE
3.2.10 to 3.3

### PR DESCRIPTION
**Pull request by arnaudbroes**

### CODE REVIEW

**Comment by arnaudbroes** [comment]
FYI, Grunt will fail on this and that is fine.

**Comment by michaeltorbert** [comment]
@wpsmort For testing, just quickly test that the 3.2.10 changes still work.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
@michaeltorbert did 2 small changes (delete duplicate file and fix path).

**Pull request merged**
