### PR TITLE
Improve look of meta box and menus

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #1168

## Proposed changes

Improves the general appearance of our meta box and menus.

## Types of changes

- Improves existing functionality

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

Check the meta box and all menus and make sure they look good.

## Further comments

This will have to be code reviewed in concert with myself on a call since GitHub thinks the whole CSS file changed. It didn't.

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@wpsmort I'm aware that the OG:object type dropdown menus haven't been restyled yet. That's something that will require more work so I won't include that in 3.0.

**Comment by arnaudbroes** [comment]
I'm surprised no one ever saw this before and created an issue for it but I've also fixed the alignment of the settings in the Additional Pages section (XML Sitemap/Video Sitemap menus).

image

**Comment by wpsmort** [comment]
@arnaudbroes This looks good, but I have some recommended changes and some issues with RTL styles:

1. Remove the inline styles you're adding to admin/aioseop_module_class.php and modules/aioseop_sitemap.php.  Styles should be in the css file unless there's a specific reason for having inline styles.

2. Increase the border-radius for radials to 8px so that radials are circles.  Currently they look too much like checkboxes.

3. Remove the left margin that is applied using inline style to the Add Rule button on the Robots.txt module so that the button aligns with the left side of the form and table (https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/1eb745292046d926fecf7ecf65663807cde4cce3/modules/aioseop_robots.php#L63).

4. Add a gutter between the button at the top of all settings screens and the first meta box (and the bottom of the mailing list box).  There's a gutter at the bottom between the last meta box and the button at the bottom of all settings screen but not one at the top.

5. Change the text color of .ui-sortable-handle span from to black.  I'm not a fan of the dark grey.

6. Remove the width restriction on the Preview Snippet.  If you enter a long SEO description you'll see that the Preview Snippet is width restricted to 63% of the container.  The CSS for this also affects the width of the other containers on the Edit Post screen (https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/1eb745292046d926fecf7ecf65663807cde4cce3/css/modules/aioseop_module.css#L1385).

7. The Analyze button on the SEO Data Import screen needs to be styled the same as a secondary button. 

8. Improve the usability of all textarea fields when there is a scroll bar present.  Currently it's not easy to scroll or drag to resize the textarea when the scroll bar is present.  This only affects webkit browsers (Safari and Chrome).  See screenshot below.

Screen Shot 2019-05-28 at 11 55 24 AM

9. The text in the textarea where the robot.txt output is displayed is hard to read in Safari only.  See screenshot below.

Screen Shot 2019-05-28 at 1 12 12 PM

10. There are some problems with RTL styling.  Specifically checkboxes, character counters, tabs, quick edit, and feature manager.  See screenshots below.

Screen Shot 2019-05-28 at 12 49 57 PM

Screen Shot 2019-05-28 at 1 05 05 PM

Screen Shot 2019-05-28 at 1 05 13 PM

Screen Shot 2019-05-28 at 12 49 39 PM

Screen Shot 2019-05-28 at 1 08 52 PM

**Comment by wpsmort** [comment]
@arnaudbroes There are some additional styling issues as follows:

1. The alignment of the top of the meta boxes and sidebar boxes is off.  See screenshots below.

Screen Shot 1

Screen Shot 2

2. The right alignment of the AIO meta box on the Edit Post screen is off.  See screenshot below.

Screen Shot 3

3. I'd also recommend making the padding for textarea fields consistent, i.e. padding: 10px; 
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/1eb745292046d926fecf7ecf65663807cde4cce3/css/modules/aioseop_module.css#L174

4. The alignment of the Reset button at the bottom of many screens is off.  See screenshot below.

Screen Shot 4

5. The buttons on the Feature Manager needs a margin bottom.  See screenshot below.

Screen Shot 6

6. The area in the Robots module overflows the meta box.  The meta box needs a padding right.  See screenshot below.

Screen Shot 2019-05-30 at 11 14 18 AM

7. There's one RTL issue with the Pro module in the Feature Manager.  The title "Video Sitemap" should be centered.  See screenshot below.

Screen Shot 5

**Comment by arnaudbroes** [comment]
@wpsmort I fixed all issues besides (2) and (5) because I can't figure out a fix. Both are pre-existing I believe and are a pain because the underlying HTML code is difficult to work with.

**Comment by michaeltorbert** [comment]
Since 2 and 5 are pre-existing let's just open an issue for them for 3.1 so we don't hold up this release any longer.

**Comment by wpsmort** [comment]
We fixed 5 and I've opened issue #2533 for 2.

This is tested and is good.

**Pull request merged**
