### PR TITLE
Improve look of tooltips

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #2283

## Proposed changes

Improves the look of our current tooltips.

## Types of changes

What types of changes does your code introduce?

- Improves existing functionalty

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

Check our new tooltips and make sure they look good.

## Further comments

FYI, we have https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2435 open to improve the content and formatting of our help text.

### CODE REVIEW

**Comment by wpsmort** [comment]
@arnaudbroes As discussed, this affects the styling of the tabs in the AIOSEOP meta box on the Edit Post screen as shown below:


Screen Shot 2019-05-14 at 4 49 34 PM

**Comment by arnaudbroes** [comment]
@wpsmort good catch! I took care of it.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
@wpsmort can you quickly test this again? Ben added a really nice looking 3D effect to it.

**Comment by wpsmort** [comment]
This is tested and is good.

**Pull request merged**
