### PR TITLE
Video XML Sitemap - Remove the Scan button

### PR DESCRIPTION
**Pull request by contactashish13**
https://github.com/semperfiwebdesign/aioseop-pro/issues/225

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@contactashish13 I built Pro and this doesn't remove the button; but it breaks the functionality though. Let me know in case I did something wrong.

image

**Comment by contactashish13** [comment]
@arnaudbroes can you please list down the steps you took to test this as the changes are there in both the free and pro repos?

**Comment by arnaudbroes** [comment]
@contactashish13 download the plugin at the time of the commit, drop the Pro directory from the latest release for AIOSEOP Pro in the root directory of the commit version and set the boolean at the beginning of the all_in_one_seo_pack.php file to 'true' so the Video XML Sitemap module appears.

**Comment by contactashish13** [comment]
@arnaudbroes Are you sure about this? 

> drop the Pro directory from the latest release for AIOSEOP Pro in the root directory of the commit version 

If the changes for this issue are in the pro repo as well, shouldn't you be taking the folder from that commit?

**Comment by michaeltorbert** [comment]
@arnaudbroes I think the confusion comes from the fact that in this issue, changes have been made to both the /pro/ directory as well as the shared code (free). So you need the pro directory from the pro repo's PR https://github.com/semperfiwebdesign/aioseop-pro/pull/434/files rather than the latest Pro directory.

**Comment by arnaudbroes** [comment]
@michaeltorbert that did it, thanks. 

This has been tested. Needs code review.

**Pull request merged**
