### PR TITLE
Add placeholder/upsell for cat/tag/taxonomy titles

### PR DESCRIPTION
**Pull request by contactashish13**
#738

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 This is good.  One minor change, please change the URL for the link to:

https://semperplugins.com/all-in-one-seo-pack-pro-version/?loc=taxonomies

**Comment by michaeltorbert** [comment]
@wpsmort I've made the change.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by wpsmort** [comment]
@EkoJR If this can be improved by adding it to your new notices class then please submit the code changes for this or a new PR.

**Comment by michaeltorbert** [comment]
This should be a permanent message where AIOSEOP would be, not an admin notice.

**Comment by arnaudbroes** [comment]
@michaeltorbert it's already a permanent notice, I was just commenting on what Ben proposed so this can be reopened.  Sorry for the confusion. :-)

**Comment by arnaudbroes** [comment]
@contactashish13 we've decided that @EkoJR will create a non-dismissable notice using the class he recently created so I'll go ahead and close this PR and assign the issue to him.

**Pull request closed without merging**
