### PR TITLE
Add last change timestamp for homepage & tax terms

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #262

## Proposed changes

Adds the Last Change timestamp for the homepage and taxonomy terms.
This supports taxonomy terms with multiple attached post types.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

1. Check whether the Last Change timestamp for the homepage is based on the last modified Post.

2. Check whether the Last Change timestamp for taxonomies (Categories, Tags, custom taxonomies) is based on the last modified post of the post type that is assigned to it.

3. Check whether the Last Change timestamp for taxonomies with multiple attached post types* is based on the timestamp of the last modified post that is assigned to it, regardless of its type. 

_*e.g. use the Custom Post Type UI plugin to create a new custom taxonomy with Posts and Pages as its post types. Assign both a Post and Page to it; then update them randomly and check whether the timestamp is based on the one that was most recently updated._

You might also want to test this on a large test site to see if this doesn't impact performance too much, but it shouldn't based on my test results.

### CODE REVIEW

**Comment by wpsmort** [comment]
@arnaudbroes There are some bugs with this PR:

1. When sitemap indexes is disabled and the homepage is set to display latest posts, there is no Last Change date.
2. Publishing or modifying a post changes the Last Change date for ALL categories and tags, not just the category and tag for that post.  This happens with any post type and with sitemap indexes enabled or disabled.
3. Publishing or modifying a CPT post doesn't change the date of the post type archive. This happens with sitemap indexes enabled or disabled.
4. Publishing or modifying a post doesn't change the Last Change date of the Blog page set under Reading Settings. This happens with sitemap indexes enabled or disabled. This is most likely the same bug as 3 above.

**Comment by arnaudbroes** [comment]
@wpsmort these issues should have been fixed now.

**Comment by wpsmort** [comment]
@arnaudbroes I found that item 3 above is not fixed.  Adding/modifying a new post in a CPT doesn't affect the date of the post type archive.

I also found one new bug.  When you override the priority and frequency for a specific taxonomy, then the priority and frequency for all other taxonomies is empty.  Here's the steps to reproduce:

1. Go to the XML Sitemap settings and in the Priorities section, choose "Select Individual" next to Taxonomies
2. Now select "0.1" next to Categories Taxonomy
3. Next, in the Frequencies section, choose "Select Individual" next to Taxonomies 
4. Now select "Hourly" next to Categories Taxonomy and click Update Sitemap
5. View the sitemap and you should see that all categories are set based on the settings above but all other taxonomies are missing the priority and frequency.  See screenshot below:

Screen Shot 2019-07-16 at 10 13 25 AM

**Comment by arnaudbroes** [comment]
@wpsmort the second bug is pre-existing so I've opened an issue for it here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2730. We'll first want to decide whether we still want to include the prio/freq attributes in our sitemap.

**Comment by arnaudbroes** [comment]
@wpsmort I'm still not able to reproduce that bug. Can we hop on a call?

**Comment by arnaudbroes** [comment]
@wpsmort the CPT/archive page bug has been fixed (as you confirmed earlier) but I've also done some of the refactoring I mentioned so this is now ready to be retested again.

**Comment by EkoJR** [comment]
After getting everything configured for PHP 5.4 (which wasn't easy), phpMyAdmin 4.1.14, and installing PHP Unit 4.*. I found that it is `\Test_Sitemap::test_only_pages()` that is *terminating*.

Looks like it is terminating at modules/aioseop_sitemap.php:3265 `$index = array_search( $static_page_url, array_column( $urls, 'loc' ) );`

Seems `array_column()` isn't available in PHP 5.4 https://www.php.net/manual/en/function.array-column.php

# Solution

Replace 

`$index = array_search( $static_page_url, array_column( $urls, 'loc' ) );`

with

```
$url_locs = array_combine( array_keys( $urls ), wp_list_pluck( $urls, 'loc' ) );
$index = array_search( $static_page_url, $url_locs );
```


# Additional Details

*Callstack*

aioseop_sitemap.php:3265, All_in_One_SEO_Pack_Sitemap->update_static_page_timestamp()
aioseop_sitemap.php:3221, All_in_One_SEO_Pack_Sitemap->get_homepage_timestamp()
aioseop_sitemap.php:2484, All_in_One_SEO_Pack_Sitemap->get_sitemap_without_indexes()
aioseop_sitemap.php:2501, All_in_One_SEO_Pack_Sitemap->do_simple_sitemap()
aioseop_sitemap.php:1849, All_in_One_SEO_Pack_Sitemap->do_sitemaps()
class-wp-hook.php:288, call_user_func_array:{C:\WebProjects\UW-WPDev-aioseop\wordpress-develop\src\wp-includes\class-wp-hook.php:288}()
class-wp-hook.php:288, WP_Hook->apply_filters()
class-wp-hook.php:310, WP_Hook->do_action()
plugin.php:465, do_action()
aioseop_module_class.php:3036, All_in_One_SEO_Pack_Module->handle_settings_updates()
aioseop_functions.php:718, aioseop_ajax_save_settings()
class-wp-hook.php:286, call_user_func_array:{C:\WebProjects\UW-WPDev-aioseop\wordpress-develop\src\wp-includes\class-wp-hook.php:286}()
class-wp-hook.php:286, WP_Hook->apply_filters()
class-wp-hook.php:310, WP_Hook->do_action()
plugin.php:465, do_action()
class-aioseop-test-base.php:320, AIOSEOP_Test_Base->_setup_options()
test-sitemap.php:69, Test_Sitemap->test_only_pages()
TestCase.php:909, ReflectionMethod->invokeArgs()
TestCase.php:909, PHPUnit_Framework_TestCase->runTest()
TestCase.php:768, PHPUnit_Framework_TestCase->runBare()
TestResult.php:612, PHPUnit_Framework_TestResult->run()
TestCase.php:724, PHPUnit_Framework_TestCase->run()
TestSuite.php:722, PHPUnit_Framework_TestSuite->run()
TestSuite.php:722, PHPUnit_Framework_TestSuite->run()
TestRunner.php:440, PHPUnit_TextUI_TestRunner->doRun()
Command.php:149, PHPUnit_TextUI_Command->run()
ide-phpunit.php:299, IDE_Base_PHPUnit_TextUI_Command::main()
ide-phpunit.php:611, {main}()

**Comment by wpsmort** [comment]
@arnaudbroes As discussed, this works great with one exception as follows:

The WooCommerce Shop page last change date is not being taken from the last change date of the products.  This happens when sitemap indexes is disabled and when sitemap indexes is enabled and you're viewing the page-sitemap.xml sitemap.

**Comment by arnaudbroes** [comment]
@wpsmort I actually forgot the Woocommerce shop page was taken care of in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2720 which is why this wasn't included in this PR. Since that was the only thing missing here, I'm assigning it to @EkoJR for code review unless you disagree.

**Pull request merged**
