### PR TITLE
XML Sitemap - Add support for images in JetPack galleries

### PR DESCRIPTION
**Pull request by contactashish13**
#1230

### CODE REVIEW

**Comment by wpsmort** [comment]
This is tested and is good.  It works with the JetPack slideshow.

**Comment by michaeltorbert** [comment]
@wpsmort Since there are new commits, this needs to be retested.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts

**Comment by wpsmort** [comment]
@contactashish13 I tested this with each of the gallery types that JetPack adds and found that this only works if you select the Slideshow gallery type (see screenshot).  It does not work if you select any of the four other gallery types.  I have a test site set up that you can test with.

screen shot 2018-07-30 at 3 33 36 pm

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and then assign back to me for testing

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is good.  Ready for code review.

**Pull request merged**
