### PR TITLE
Improved environment configuration with plugin's bootstrap #1526

### PR DESCRIPTION
**Pull request by EkoJr**
Improved environment configuration with plugin's bootstrap #1526

@contactashish13 do you approve these?

### CODE REVIEW

**Comment by contactashish13** [comment]
@EkoJr as long as the test cases already checked in work without a change, it should be okay. If that's not the case, can you please change the rest of the dependencies too?

Also I'm not sure why a separate configuration variable is required for plugins and themes. Plugins should be siblings of the AIOSEOP plugin and themes should siblings of the plugins directory, like a normal WP install.

**Comment by EkoJr** [comment]
> as long as the test cases already checked in work without a change, it should be okay.

No severe changes, but I did notice you made an addition when I rebased, but I kept the addition with the aioseop tests directory.

> Also I'm not sure why a separate configuration variable is required for plugins and themes. Plugins should be siblings of the AIOSEOP plugin and themes should siblings of the plugins directory, like a normal WP install.

The plugin is loaded in the `bootstrap.php`, but there is also need to add other repos ( like AIOSEOP Pro ). Unless something changed to allow nesting git repos. Some cases may also require investigating various Repo Versions to reproduce an issue, but it's mostly other plugins I've had to investigate in general where I've found this useful

However, it is still the same concept, and only requires setting the WP Dev directory like before. Everything else defaults to native settings, but I wanted to open it up to working on multiple repos in the same project; which seemed very useful for Free & Pro.

**Comment by contactashish13** [comment]
@EkoJr check https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1458 where I've tested for dependency on another plugin.

**Comment by EkoJr** [comment]
@contactashish13 That is because you added this Constant. Which isn't even in the master yet.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1458/files#diff-10eafd8bf5fbdde867b86fe38d30b9bbR20

**Comment by contactashish13** [comment]
@EkoJr yeah, many things are not in the master and will be "discovered" as we move from test case to test case. In this case, I've added this constant for 2 PRs that both needed to be tested with external plugins. If this suffices for the purpose you have in mind, can we use this instead?

**Comment by EkoJr** [comment]
@contactashish13 Oh ok. I'll pull some of the branches into mine and test. Especially with #1458 and see what exactly happened, because I tried keeping most of the changes mutual.

**Comment by contactashish13** [comment]
@EkoJr sure. Let me know if things don't work and you want me to change the test cases. There are only about 10 PRs so should not be a big problem.

**Comment by EkoJr** [comment]
@contactashish13 Looks like you marked it as skip. https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1458/files#diff-13d1ed975aa3625dfed14448492c176fR131 

There's also a rebased version. https://github.com/EkoJr/all-in-one-seo-pack/commits/a45c637e964d3f1807c82f411d5c1ba2d62b5c70

I also didn't see any other conflicts.

**Pull request closed without merging**
