### PR TITLE
Refactor main plugin file into a core class

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #1397

## Proposed changes

Refactors the main plugin file into a core class.

## Types of changes

What types of changes does your code introduce?

- Removing old code/functionality
- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [ ] I have added necessary documentation, or have created an issue for docs (if appropriate).

## Testing instructions
* Check to see if plugin is functional when active.
* Check plugins page to see additional links are added.
* Test scan on Opengraph settings page.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@EkoJR putting this on hold till https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/3007 is merged so you can move that into this first before I test and review.

**Comment by arnaudbroes** [comment]
@EkoJR can you resolve the merge conflict and move the code from https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/3007#event-2805699734 to the core class?

**Comment by arnaudbroes** [comment]
@EkoJR is this still in dev

**Comment by EkoJR** [comment]
@arnaudbroes Yes, I was working on it and my ISP went down.

**Comment by arnaudbroes** [comment]
I'll leave testing to @wpsmort so I can do the code review.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
This is good.

@EkoJR one small comment: versions after `@since` tags need to be expressed with 3 digits (so 3.4.0 instead of 3.4). I'm not going to hold this PR for that though.

**Pull request merged**
