### PR TITLE
 Trigger sitemap notice only when XML Sitemap module is active

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #2756

## Proposed changes

Fixes an issue where our sitemap notice is triggered even when the XML Sitemap module isn't enabled.

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [ ] Travis-ci runs with no errors.

## Testing instructions

Enable the XML Sitemap module, then enable Sitemap Indexes and set the amount of pages per index to something larger than 1,000. The notice should appear (if this is on a fresh test site). Now dismiss the notice and disable the XML Sitemap module again. Then go to the database, delete aioseop_notices and make sure the notice isn't triggered again. 

I believe this only happens when people have previously used our XML Sitemap module and the their default amount of pages was set to something larger than 1,000.

### CODE REVIEW

**Comment by wpsmort** [comment]
@arnaudbroes I tested and found that this is not removing the message completely.  It removes the text from the message box but leaves the box there.  See screenshot that shows the empty message box:

Screen Shot 2019-09-10 at 11 19 32 AM

**Comment by arnaudbroes** [comment]
@wpsmort this can be retested.

**Comment by wpsmort** [comment]
@arnaudbroes I tested this again and the notice is being displayed when the Sitemap module is deactivated.  I think the problem is that the code you've added is in modules/aioseop_sitemap.php and that won't run if the Sitemap module is deactivated.

**Comment by wpsmort** [comment]
Arnaud and I tested this together and couldn't get the notice to reappear when the Sitemap module is activated and Sitemap Indexes is disabled, or it's enabled and number of pages per sitemap is set to over 1000.

**Comment by arnaudbroes** [comment]
Closing this as this was just a low effort to fix this quickly. In retrospect, the whole notice class/code probably needs a bit of work.

**Pull request closed without merging**
