### PR TITLE
Pagination not applied to custom canonical URLs

### PR DESCRIPTION
**Pull request by contactashish13**
#948

### CODE REVIEW

**Comment by contactashish13** [comment]
@michaeltorbert I don't know what's going on in this PR. I tried to resolve the conflicts and once I try to merge, it says "This page is out of date. Start over" (screenshot). Tried doing this multiple times and its the same every time.

image

**Comment by michaeltorbert** [comment]
If you aren’t sure how to fix it, maybe it’s best to close this PR and make a new one.

**Comment by michaeltorbert** [comment]
Are these the only changes (other than automated test)? If so, surely it would only take a few minutes to recreate in another PR?

screen shot 2018-10-10 at 3 51 33 pm

**Comment by michaeltorbert** [comment]
@contactashish13 Are these the only changes (other than automated test)? If so, surely it would only take a few minutes to recreate in another PR?

screen shot 2018-10-10 at 3 51 33 pm

**Pull request closed without merging**
