### PR TITLE
Fixed icon refresh effect in Admin Menu #292

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #292

### CODE REVIEW

**Comment by EkoJR** [comment]
@wpsmort Looks everything is correct, and shouldn't change the logo. If the menu icon is still showing a cog wheel, then let me know.

menu_icon_fix

**Comment by wpsmort** [comment]
@EkoJR This is still showing the cog dashicon.  I tested on a brand new site just to make sure it wasn't browser caching.

screen shot 2018-08-17 at 12 33 29 pm

**Comment by EkoJR** [comment]
As discussed, it would be the file structure causing the issue. Renaming the folder back to the original `all-in-one-seo-pack` should fix the issue.

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is good.  Ready for code review.

**Pull request merged**
