### PR TITLE
Make it easy to test PRO features in the free plugin with minimal changes

### PR DESCRIPTION
**Pull request by contactashish13**
#2305

### CODE REVIEW

**Comment by michaeltorbert** [comment]
What is the benefit of this over just having `define( 'AIOSEOPPRO', true );` in wp-config.php?

**Comment by contactashish13** [comment]
As I mentioned on the call, the free plugin deactivates itself when it sees pro is true. The mimic constant prevents that from happening.

**Comment by arnaudbroes** [comment]
@contactashish13 does this need discussion or testing now? There's no stage label.

**Comment by contactashish13** [comment]
@arnaudbroes Actually, can you test the below 2 ways just to verify that you see the same behavior that I do? 

**Old method**
1. Make `define( 'AIOSEOPPRO', true );`
2. Copy pro folder
3. Test
(here the free plugin gets deactivated automatically after 1-2 refreshes)

**New method**
1. Make `define( 'AIOSEOPPRO_MIMIC', true );`
2. Copy pro folder
3. Test

**Comment by arnaudbroes** [comment]
@contactashish13 that isn't a full solution since there are a number of checks in the plugin for the AIOSEOPPRO variable. For instance, AIOSEOPPRO_MIMIC doesn't disable the upgrade links throughout the plugin nor does it activate Pro features like the Video XML Sitemap. 

What's the advantage for us of having both the free and Pro version activated? Also, I don't think this variable would allow that as the folder name also needs to be different.

**Comment by michaeltorbert** [comment]
Yeah I must admit I'm not sure I see the benefit either. Creating Pro is extremely easy. You just drop in the Pro directory and change the constant + plugin name.

**Comment by arnaudbroes** [comment]
@contactashish13 feel free to reopen this if you can think of a good reason why we need to make this "easier" (as it is already extremely easy like Michael said) but in the meanwhile I'm going to close this PR.

**Comment by contactashish13** [comment]
No offence but I feel like no one's actually tried this :) I have tried the "easy" method and it deactivates the plugin. It makes it impossible, not merely difficult, to test a change. I have tried to list down the different scenarios and out of them the easiest is this. Nevertheless, if you guys feel differently, you can keep this closed.

**Comment by michaeltorbert** [comment]
@contactashish13 It won't deactivate if you change the directory name, for instance appending "-pro".  The deactivation code specifically looks for a plugin directory named "all-in-one-seo-pack". https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/all_in_one_seo_pack.php#L510

**Comment by contactashish13** [comment]
Ok, so that doesn't make it the easiest method then. Because then development is not seamless. I have to change the folder name, copy the headers - don't you think from a development point of view that is too cumbersome compared to what I'm suggesting? The likelihood of checking in the main file with wrong headers is also high.

**Comment by michaeltorbert** [comment]
They're both about the same number of steps, but one doesn't require permanent changes to the code.

**Comment by contactashish13** [comment]
Let me list it down:

1. Copy headers
2. Change define
3. Change folder name
4. Make/test changes
5. Revert folder name so that commits can happen
6. Change define
7. Commit


Suggested method:

1. Change define
2. Make/test changes
3. Change define
4. Commit

**Pull request closed without merging**
