### PR TITLE
Video XML Sitemap - Display thumbnails for all videos in a post #289

### PR DESCRIPTION
**Pull request by contactashish13**
Issue https://github.com/semperfiwebdesign/aioseop-pro/issues/289

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 This is tested and is good.  Please sync your branch with the latest code from our dev branch and submit this back to me for final testing and code review.

**Comment by contactashish13** [comment]
@wpsmort done

**Comment by wpsmort** [comment]
@contactashish13 Please confirm you used the Github method for syncing a fork (https://help.github.com/articles/syncing-a-fork/) to sync your branch with our upstream branch.

**Comment by contactashish13** [comment]
@wpsmort this PR does not seem to have any other commits

image

**Comment by wpsmort** [comment]
New PR #997 opened.

**Pull request closed without merging**
