### PR TITLE
Meta descriptions aren't output when using ACF macro in Description Format

### PR DESCRIPTION
**Pull request by contactashish13**
#960

### CODE REVIEW

**Comment by wpsmort** [comment]
This is tested and is good.  This is ready for code review.

**Comment by michaeltorbert** [comment]
@contactashish13 Why did you take out part of the conditional here? https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1483/files#diff-4e533641bc4be27bca19bde1a2b60fe9L3843

**Comment by contactashish13** [comment]
@michaeltorbert I have added a comment to explain that https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1483/files#diff-4e533641bc4be27bca19bde1a2b60fe9R3843

**Comment by wpsmort** [comment]
@contactashish13 I tested this and found that whilst it does work fine, it overrides the aioseop_description filter.  The filter should always override any other description entered.

**Comment by contactashish13** [comment]
@wpsmort I'm not sure I understand which filter you are referring to here.

> The filter should always override any other description entered.

**Comment by EkoJR** [comment]
@contactashish13 It doesn't appear I've touched the `aioseop_description_full` filter, and looks like that code has been there for 3+ years. It's just the `aioseop_description` filter when I had to make a correction after an update; which was to reverted the hook back to its previous location.

**Comment by wpsmort** [comment]
@EkoJR The filter I am referring to in my testing is the aioseop_description filter (https://semperplugins.com/documentation/aioseop_description/).  This should always override any other SEO Description setting in the plugin.  Basically, if someone has gone to the lengths of adding API filter code to their site to set a description then that's the description they want to use.

**Comment by contactashish13** [comment]
@EkoJR just to reiterate @wpsmort's point, the code you have added makes `aioseop_description_full` runs after the `aioseop_description` is called. Can you check if this is valid?

**Comment by EkoJR** [comment]
@contactashish13 That's not any code that I have added. It has been like that for 3+ years. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blame/301f38f04fd45f5d1ec60c20162c7c315cc05247/aioseop_class.php#L3822

Initial upload (3 years ago) -  `aioseop_description_full` still runs after the `aioseop_description` is called.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blame/cefd0459e651644364a6b4707aeabd1162736947/aioseop_class.php#L2017

These are the changes that were made for the Description update; rebased into 1 commit to make it easier to see the changes.
https://github.com/EkoJR/all-in-one-seo-pack/commit/6d4d94999b7ef8be5fc28914db736591336c40c8

**Comment by contactashish13** [comment]
@EkoJR my bad.

@wpsmort he is right. `aioseop_description_full` runs after the `aioseop_description` is called since the beginning. Do you want this changed? I don't know what all this could impact.

**Comment by wpsmort** [comment]
@contactashish13 I did some further checking and found that the issue with the aioseop_description filter is not new and so I've opened a new issue for it and we can ignore it for the purposes of this PR.  

If you can resolve the merge conflict here then this PR will be ready for code review.

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is good. Ready for code review.

**Pull request merged**
