### PR TITLE
 Changed Support Metabox Icons to Font-Icons

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #289 #1154 

## Proposed changes

Changes the icons in Support sidebar metabox to font icons.

## Types of changes

- New feature (non-breaking change which adds functionality)
- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

1. Activate plugin.
2. Go to AIOSEOP General Settings.
3. Scroll to Support sidebar metabox, and icons should be font icons.

## Further comments

support metabox

### CODE REVIEW

**Comment by arnaudbroes** [comment]
This is good, although I think the icons are too big so I've made them a bit smaller.

I'll pass this back to @EkoJR first before code review because I wanted to ask whether there is a reason for all the redundant CSS on lines 23-34 and lines 38 till 48 (with the exception of line 39)?

If I remove all of these lines (https://pastebin.com/S59NgUbQ), the icons still look the same.

**Comment by arnaudbroes** [comment]
Also, does this have a specific issue? If so, please add it to the PR description above.

**Comment by EkoJR** [comment]
It's been a long while, but I think there were two instances where the icon needed to be applied.

It's also part of [Fontastic](http://app.fontastic.me) styling, so I left it as is.

**Comment by arnaudbroes** [comment]
@EkoJR great, then I'll go ahead and pass all of these on for code review.

**Comment by michaeltorbert** [comment]
I edited the PR description to add the appropriate issue numbers. It previously was just the number for this pull request.

**Pull request merged**
