### PR TITLE
Remove the Link From Virtual Robots.txt option #535

### PR DESCRIPTION
**Pull request by contactashish13**
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/535

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@contactashish13 I added the requirements for this to #535. Currently, the XML Sitemap menu is correctly indicating whether or not the sitemap link is added to the virtual robots.txt file. However, we also need to automatically the sitemap link to the virtual robots.txt file by default. Then there should be filter hook (no longer a setting) for users who want to disable this.

**Comment by wpsmort** [comment]
@contactashish13 I tested this and when I first updated my sitemap the indicator showed a green checkmark and the link to my sitemap appeared in the default WordPress robots.txt.  However, when I changed settings for my sitemap by unchecking Enable Sitemap Indexes and checking Create Compressed Sitemap I got a red X and the link to my sitemap no longer appeared in the default WordPress robots.txt.  I couldn't figure out why the link suddenly disappeared and the red X was not helpful.  I also tested on a brand new site and couldn't get a green checkmark.

I think we need to output something in the debug log or in our own log file (if Log Important Events) is enabled) to say why the link could not be added to the virtual robots.txt.

Also, please provide an example of how to use the new filter.

**Comment by contactashish13** [comment]
@wpsmort have fixed this and I have added the filter details in the issue.

**Comment by contactashish13** [comment]
@wpsmort except for the first 2 lines (which I've fixed), this seems to be an preexisting bug. Please confirm

**Comment by wpsmort** [comment]
This is tested and is good.  The PHP notices and warning were gone and the filters both worked.

Ready for code review.

**Comment by michaeltorbert** [comment]
On a brand new installation, when activating the sitemap module, I get the following:

`( ! ) Warning: array_key_exists() expects parameter 2 to be array, null given in /app/public/wp-content/plugins/all-in-one-seo-pack-cb979456707e7a0eb1b0a7c29694490b8bc7a84c/inc/aioseop_functions.php on line 1110
--`

This is likely from there being no module information saved to the db yet.

**Pull request closed without merging**
