### PR TITLE
Change Meta Description to be longer #1395 PR #1454

### PR DESCRIPTION
**Pull request by EkoJr**
Change Meta Description to be longer #1395 PR #1454

Manual Descriptions aren't trimmed.

### CODE REVIEW

**Comment by wpsmort** [comment]
@EkoJr  I have tested this PR and have the following requests:

1. Can you update your branch so it matches our Master which is at version 2.4.3 please.
2. Can you let me know what the filter is for changing the cutoff.  See the comment here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1395#issuecomment-355035771
3. Can you change the text under the Home Description field to reflect the wording "Most search engines use a maximum of 230-320 chars for the description."  See screenshot.

screen shot 2018-01-04 at 3 57 43 pm

**Comment by EkoJr** [comment]
1. I updated all my branches, and added 2.4.3. Did you want me to rebase onto 2.4.3 as well?
2. The filter was a pre-existing filter `aiosp_dont_truncate_descriptions`. [Located here](https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1454/files#diff-4e533641bc4be27bca19bde1a2b60fe9R2564)
```
$description = apply_filters(
    'aioseop_description',
    $description,
    empty( $aioseop_options['aiosp_dont_truncate_descriptions'] )
);
```
3. I saw another 'if' check, which checks if it is already set, and may be the cause of it...but was unsure what implications it had. [all-in-one-seo-pack/admin/aioseop_module_class.php on Line 2257](https://github.com/EkoJr/all-in-one-seo-pack/blob/f17df674552dc4204130dee721fbdcfa1c2c3b7b/admin/aioseop_module_class.php#L2257)

**Comment by wpsmort** [comment]
@EkoJr:  I see the text that needs to be changed on line 2268 of that file.  Can you make that change and then this should be fine.

**Comment by EkoJr** [comment]
That line was one of the changes I tried to make, but wasn't able to get it to work with the rest of the code. Which resulted in inserting the difference with the variable that the inserts the data.

**Comment by EkoJr** [comment]
It is quite possible something else is setting the size for that setting. Since it seemed to have a check for that.

**Pull request merged**
