### PR TITLE
#593 Applies SEO ready encoding/decoding of html entitites.

### PR DESCRIPTION
**Pull request by amostajo**
This is for issue #593 

Applies SEO ready encoding and decoding of html entitites for
descriptions and titles.

### CODE REVIEW

**Comment by wpsmort** [comment]
@amostajo I tested this PR and it does fix the problem with double quotes, however, I found some bugs with the code:

1 - Capitalized words in the description in the preview snippet, Description field on the Main Settings tab, and Description field on the Social Settings tab changed from capitalized to lowercase, .i.e. "This post" changed to "this post".   See screenshot below.

2 - Capitalized words in the title tag, meta description, OG meta and Twitter meta in the source code changed from capitalized to lowercase, .i.e. "This post" changed to "this post".  See screenshot below.

screen shot 2017-06-08 at 10 53 56 am
screen shot 2017-06-08 at 10 57 47 am

**Comment by amostajo** [comment]
@wpsmort Fixed.

**Comment by wpsmort** [comment]
@amostajo I have confirmed that the latest commit fixed the issue with capitalized words being converted to lowercase.  

I did find one other issue here, when testing with PHP version 5.2 I found that some of the meta tags use &quot; and some use &#8220;.  Titles use &#8220; and descriptions use &quot;.

This doesn't happen when testing with PHP v5.4 or later.

See screenshot:

screen shot 2017-06-08 at 2 14 49 pm

**Comment by amostajo** [comment]
Ahh so I we do need a custom html_entity_decode!

**Comment by amostajo** [comment]
@wpsmort Can you test it again please. In theory, everything we should be escaping most of the instances of double quotes into &quot;. Which is widely supported.

**Comment by wpsmort** [comment]
@amostajo The closing HTML tag in the title meta tags is still showing as &#8221;.  See screenshot:

screen shot 2017-06-09 at 10 54 09 am

**Comment by amostajo** [comment]
@wpsmort Added a couple more double quote entities to decode. Please test it again.

**Comment by wpsmort** [comment]
This is tested and now works fine.  I've tested with PHP versions from 5.2 to 7.1 and all work.  

This PR is now ready for code review.

**Pull request merged**
