### PR TITLE
Make "All in One SEO Pack" string untranslatable

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #2432

## Proposed changes

This makes the string "All in One SEO Pack" untranslatable again. We decided to do this in order to preserve our brand name/product name across all languages.

## Types of changes

- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

Check which strings have been changed and then check these in both the free and premium version of the plugin to see if all still look good.

**You'll have to build Pro by combining the PR in free and Pro.**

## Further comments

PR in Pro can be found here - https://github.com/semperfiwebdesign/aioseop-pro/pull/498

@michaeltorbert ping me once these changes have been pushed to translate.wordpress.org so I can check whether the string is no longer translatable.

### CODE REVIEW

**Comment by arnaudbroes** [comment]
This needs https://github.com/semperfiwebdesign/aioseop-pro/issues/487 to be solved and merged into this PR first so that the Pro strings can be checked as well.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
I'll assign this back to testing to make sure this didn't break anything considering the amount of comments I've added.

**Comment by wpsmort** [comment]
This is tested and is good.

**Pull request merged**
