### PR TITLE
Fix undefined variable: post_type

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #1798

## Proposed changes

Fixes a PHP error undefined variable: post_type. 

Removes duplicate code that wasn't conceptually applicable. Post type NoFollow checks were occuring in Taxonomy operations.

## Types of changes

What types of changes does your code introduce?
_Delete those that don't apply_

- Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

**Note: Also test noindex with nofollow settings.**

Settings 

Post Types

1. Go to General Settings.
2. Check/enable post types in 'SEO on only these Content Types'.
3. Scroll to NoIndex Settings
4. Check or Uncheck post types to NoFollow.
5. Go to post on frontend and check nofollow in <head>

Taxonomy

1. Go to General Settings.
2. Check/enable post types in 'SEO on only these Taxonomies'.
3. Go to a Term editor within a taxonomy.
4. Check/Enable 'NOFOLLOW this page/post'
5. Go to term archive on frontend and check nofollow in <head>

### CODE REVIEW

**Comment by arnaudbroes** [comment]
This looks good and can be reviewed.

**Comment by EkoJR** [comment]
I added a note to the commit (as well as in the PR description), and not sure if you saw it.

> Removes duplicate code that wasn't conceptually applicable. Post type NoFollow checks were occuring in Taxonomy operations.

The same exact operation was occuring just below where post type operations do occur, and it looks like the code I removed was unnecessarily added. It actually conflicted when the `$post_type` was set.

That is the commit/PR #1447 that I tracked down as well.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1441/files

**Comment by EkoJR** [comment]
Double checking pro settings

**Comment by EkoJR** [comment]
I had to refactor the code block for taxonomy operations. Many of the checks were crammed into 1 IF operation causing a conflict with taxonomy and post type operations. This would have to go back into testing.

**Comment by arnaudbroes** [comment]
@EkoJR there is a meta robots tag in the source code ("noindex, follow") when neither noindex/nofollow is enabled. When one of these is disabled, there are two tags.
image.

**Comment by EkoJR** [comment]
Interesting...it's actually part of WP ( https://developer.wordpress.org/reference/functions/noindex/ ), and seems to be a pre-existing issue.

**Comment by EkoJR** [comment]
@arnaudbroes I added the changes to prevent that with this PR.

**Comment by arnaudbroes** [comment]
@EkoJR this introduces a new bug I'm afraid. Checking the "NOINDEX this page/post" in the meta box for Taxonomies (I tried both Categories & Tags) doesn't work anymore.

**Comment by EkoJR** [comment]
@arnaudbroes That appears to be a pre-existing issue as well. There doesn't seem to be any reported issue on it though. It will require more in depth work to get fix it, and I don't think it can be done with this PR.

**Comment by arnaudbroes** [comment]
@EkoJR not an existing issue I'm afraid. I just tested this with v2.13.1 and it works there.

**Comment by EkoJR** [comment]
Closed to rebase and resolve merge conflicts #2646

**Pull request closed without merging**
