### PR TITLE
XML Sitemap module - Add support for RSS/Atom updates

### PR DESCRIPTION
**Pull request by contactashish13**
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/561

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflict.  Also please note that when I try to visit the RSS sitemap for the first time I get a 404 error and need to flush the permalinks and update the sitemap before it'll show the RSS sitemap.  Please look into this and resolve it.

**Comment by contactashish13** [comment]
@wpsmort done

**Comment by wpsmort** [comment]
@contactashish13 I found three problems whilst testing:

1).  I get the following error is there is a non-breaking space `&nbsp;` in the post excerpt: 

Entity 'nbsp' not defined

2).  Content is only being included or removed when you click the Update Sitemap, it's not happening dynamically.  For example, if I activate WooCommerce then products are not included in the RSS sitemap until I click Update Sitemap.  If I then deactivate WooCommerce then products don't get removed from the RSS sitemap until I click Update Sitemap again.  

3).  If there is HTML markup in the Excerpt field then it is output incorrectly because the < and > symbols are output as `&lt; &gt;`.  See screenshot:

screen shot 2018-08-20 at 4 21 37 pm

**Comment by contactashish13** [comment]
@wpsmort 

problem 1: excerpt is plain text and I'm not sure it can contain `&nbsp` unless manually added. Many things, including HTML and special characters can be manually added to the excerpt. Please confirm expected behavior.

problem 2: I see the same problems in the XML sitemap. Post types will not get included till you do not explicitly include them or exclude them. Can you please test and confirm what behavior you require?

problem 3: this is how HTML-safe text is included in the XML. Do you want this included in a different way?

**Comment by wpsmort** [comment]
@contactashish13 I tested again and the `&nbsp;` issue is now resolved.  However there are still two problems:

1. You have to refresh permalink settings in WordPress before the sitemap will resolve.  If you don't, you get a 404 page.

2. I can't get new content to appear on the RSS sitemap.  If I add a new post, edit an existing post, create a new post type or do anything else, the content doesn't appear in the sitemap.

With regards to the output of HTML tags, when I look at the RSS feed created by default by WordPress, HTML tags are correctly output but in our RSS sitemap they are not.  For example, an image in the excerpt looks like this in our RSS sitemap:

`&lt;img class=&quot;aligncenter&quot; src=&quot;https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/stsci-h-p1829b-m-2000x1230.png&quot; alt=&quot;Hello&quot; /&gt;`

But it looks like this in the WordPress RSS feed:

`Hello`

**Comment by contactashish13** [comment]
@wpsmort can you please respond to my questions in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1432#issuecomment-420721122 as they pertain to your new observations as well?

**Comment by wpsmort** [comment]
@contactashish13 As far as my new observations concerning how HTML tags are displayed in the RSS sitemap, I'd like to know if you can display them the same way as the standard WordPress RSS feed.  Here's what the WordPress RSS feed shows for my post excerpt:

```
<description><![CDATA[This is my excerpt part 1

&#160;

<strong>bold text</strong>

<img class="aligncenter" src="https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/stsci-h-p1829b-m-2000x1230.png" alt="Hello" />

This is my excerpt part 2]]></description>
```

This is what the RSS sitemap shows:

```
<description>This is my excerpt part 1

&nbsp;

&lt;img class=&quot;aligncenter&quot; src=&quot;https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/stsci-h-p1829b-m-2000x1230.png&quot; alt=&quot;Hello&quot; /&gt;

This is my excerpt part 2</description>
```

If this cannot be displayed the same then please explain why this is not possible.

**Comment by contactashish13** [comment]
@wpsmort have addressed this.

**Comment by wpsmort** [comment]
@contactashish13 I'm still experiencing the problem where I have to refresh permalinks before I can view the sitemap.rss file.  If I don't then I get a 404 error when going to the RSS sitemap.

**Comment by contactashish13** [comment]
@wpsmort please try now.

**Comment by wpsmort** [comment]
This is tested and is good.  Ready for code review.

**Pull request merged**
