### PR TITLE
Add columns to taxonomy screens

### PR DESCRIPTION
**Pull request by contactashish13**
issue https://github.com/semperfiwebdesign/aioseop-pro/issues/34 (edited by @michaeltorbert to add the issue)

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@contactashish13 Can you resolve this conflict?

**Comment by wpsmort** [comment]
@contactashish13 I tested this but it does not add any columns to the taxonomy screen.  See screenshot:

screen shot 2019-02-25 at 6 22 53 pm

**Comment by michaeltorbert** [comment]
Looks like two functions were added but nothing calls them. Should there be a Pro component to this?

**Comment by michaeltorbert** [comment]
Closing this for the following reasons:

1) The issue had been marked on hold pending another issue, and should have never been done to begin with.
2) This code is not production ready and does not function at all, as it's lacking the filter hooks needed to execute.
3) This code should be in Pro.

**Pull request closed without merging**
