### PR TITLE
handle scheme-less urls

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@contactashish13 I'm confused why this fixes anything. It looks like it's just changing it to Yoda conditions.

**Comment by contactashish13** [comment]
@michaeltorbert this part of the code is new: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1286/commits/bd0ad3feb94378118b2cbb966dd27f5d1aa64e1b#diff-3e5dc9d9c608686bd97b350c372e3a6aR120

**Comment by michaeltorbert** [comment]
@contactashish13 Yep. My bad, I totally missed that. My eyes need a break.

**Comment by michaeltorbert** [comment]
This fixes #1390 #1246 and @1283
For #1246 instead of ignoring URLs it adds the fully qualified domain name

**Comment by wpsmort** [comment]
This is tested.  I tested each issue covered by this PR and made sure that GWT did not report any errors with the XML Sitemap.  This is ready for code review.

**Pull request merged**
