### PR TITLE
Add sitemap optimization

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2008

## URL to Post IDs Filter
Delete & Disable Transient Data; for testing peak performance.
```
function aioseop_remove_set_transient_url_postids() {
	remove_action( 'shutdown', 'aiosp_common::set_transient_url_postids' );
	if ( is_multisite() ) {
		delete_site_transient( 'multisite_aioseop_attachment_url_postids', self::$attachment_url_postids, 24 * HOUR_IN_SECONDS );
	} else {
		delete_transient( 'aioseop_attachment_url_postids', self::$attachment_url_postids, 24 * HOUR_IN_SECONDS );
	}
}
add_action( 'shutdown', 'aioseop_remove_set_transient_url_postids', 9 );
```

## Query Step Filter
Used to control which query steps are used.

```
/**
 * Skip heavy query step.
 *
 * @param $query_step
 * @return int
 */
function aioseop_post_images_step_1( $query_step ) {
	switch ( $query_step ) {
		case 2:
			$query_step++;
			break;
	}

	return $query_step;
}
add_filter( 'aioseop_post_images_query_step', 'aioseop_post_images_step_1' );

/**
 * Fire target query steps on every load.
 * Note: It's best not to use all 3, and value 2 is a heavy query step.
 *
 * @param $query_step
 * @return int
 */
function aioseop_post_images_step_2( $query_step ) {
	return array( 0, 1, 2 );
}
//add_filter( 'aioseop_post_images_query_step', 'aioseop_post_images_step_2' );

/**
 * On initial step ( 0 ), set the query step to target step. Default set the step as finished.
 *
 * @param $query_step
 * @return int
 */
function aioseop_post_images_step_3( $query_step ) {
	switch ( $query_step ) {
		case 0:
			$query_step = 2;
			break;
		default:
			$query_step = 3;
			break;
	}

	return $query_step;
}
//add_filter( 'aioseop_post_images_query_step', 'aioseop_post_images_step_3' );

/**
 * On initial step ( 0 ), set the query step to do all query steps. Default set the step as finished/skip.
 *
 * @param $query_step
 * @return int
 */
function aioseop_post_images_step_4( $query_step ) {
	switch ( $query_step ) {
		case 0:
			$query_step = array( 0, 1, 2 );
			break;
		default:
			$query_step = 3;
			break;
	}

	return $query_step;
}
//add_filter( 'aioseop_post_images_query_step', 'aioseop_post_images_step_4' );
```

### CODE REVIEW

**Comment by wpsmort** [comment]
I tested this on the two cloned user sites.  Whilst it is an improvement over v2.9 code, it still doesn't get us back to where we were with v2.8.  Memory usage is still high but more concerning is the number of seconds it takes to load the sitemap.  I discussed this with @EkoJR and he is going to look at optimizing the database queries even further.

**Comment by EkoJR** [comment]
@wpsmort I took another look on xDebug's profiler to check on optimization, and this function is no longer being flagged. However, there other functions that could be optimized, but it's outside this new function.

The other functions potentially in question were...
`All_in_One_SEO_Pack_Sitemap->get_prio_from_posts()`
`All_in_One_SEO_Pack_Sitemap->get_images_from_post()`
`All_in_One_SEO_Pack_Sitemap->get_prio_calc()`
`All_in_One_SEO_Pack_Sitemap->get_image_attributes()`
`All_in_One_SEO_Pack_Sitemap->parse_content_for_images()`

**Comment by EkoJR** [comment]
This is available for testing, but will still need PHPUnit tests resolved.

**Comment by wpsmort** [comment]
@EkoJR Please resolve the merge conflicts and assign to me for testing.

**Comment by EkoJR** [comment]
Close to rebase & resolve merge conflicts #2086

**Pull request closed without merging**
