### PR TITLE
#687 Adds WPML support for compatibility with sitemap rendering on different languages

### PR DESCRIPTION
**Pull request by amostajo**
Adds WPML support for compatibility with sitemap rendering on different languages. #687

### CODE REVIEW

**Comment by wpsmort** [comment]
Please see my feedback in #687.  I tested today and this currently doesn't work for the one Language URL Format setting of Language name added as a parameter

**Comment by wpsmort** [comment]
@amostajo Is this PR ready for testing or do you need to create a new PR?

**Comment by wpsmort** [comment]
This is tested with all three language options in WPML and confirmed that all three now work.  This needs a code review.

**Comment by michaeltorbert** [comment]
Also this fixes #865

**Pull request merged**
