### PR TITLE
Fixed whitespace in Settings & Edit Page

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #1198

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@EkoJR Chrome & Firefox look good, but IE11 doesn't.

image

**Comment by arnaudbroes** [comment]
@wpsmort it's just some CSS so I'll assign this to you for code review.

**Comment by wpsmort** [comment]
@arnaudbroes Code review is complete.  However, has this been tested with an RTL language to confirm that none of these changes affect the layout?

**Comment by arnaudbroes** [comment]
@wpsmort good thing you mentioned RTL, I did not. 

@EkoJR there still is a minor issue with RTL languages (e.g. Japanese). Is it possible to make that specific element expand to the left instead of right as its content gets longer?

image

**Comment by wpsmort** [comment]
Code review completed and everything is good.

**Pull request merged**
