### PR TITLE
Pro - Use WooCommerce Product Image for OG Image

### PR DESCRIPTION
**Pull request by contactashish13**
https://github.com/semperfiwebdesign/aioseop-pro/issues/186

### CODE REVIEW

**Comment by contactashish13** [comment]
@michaeltorbert what needs to be done here?

**Comment by michaeltorbert** [comment]
@contactashish13 Nothing, mistake on my part.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and assign back to me for testing.

**Comment by contactashish13** [comment]
@wpsmort I don't think I can resolve the conflicts in `modules/aioseop_opengraph.php` as it seems the entire file has changed. I believe the problem is a difference in the file endings which is why it shows the entire file has changed. 

@michaeltorbert this is one strong reason for implementing grunt in the commit process. It makes everything uniform.

**Comment by michaeltorbert** [comment]
@contactashish13 Agree on grunt. Feel free to take charge of implementing that once we've cleared out more PRs.

Wouldn't it be easiest to simply redo this in another PR? The changes were small and it may just take copy/pasting these two bits of code. https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1442/commits/946affb352b5db3c01a7b25568dd9691a843c1ca

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is good.  Ready for code review.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and assign back to me for testing.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and assign back to me for testing.

**Pull request merged**
