### PR TITLE
Add Schema to AMP plugin

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #506 & #2875

## Proposed changes

This add AIOSEOP's Schema data to the AMP plugin, and disables AMP's Schema.

This also fixes a loose comparator causing an unexpected return; which is intended for aioseop_amp_description filter.  #2875

Both issues have been included since #2875 is more of a refactor, and #506 is dependant on #2875 changes.

## Types of changes

- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [x] I have added necessary documentation.

## Testing instructions

1. Install and Activate AMP plugin.
2. Go-to/Create a post with no AIOSEOP Description.
3. Go to view post on frontend.
4. Click AMP on the top Admin menu to render page as AMP.
5. Inspect code, and check for any `<script type="application/ld+json">`.

There should be AIOSEOP's Schema, and AMP's Schema should not exist on the post/page.

### Disable AIOSEOP's Schema on AMP Hook Test

1. Create a child theme.
2. In the theme's file directory, edit `functions.php`.
3. Add `add_filter( 'aioseop_amp_schema', '__return_false' );`
4. Inspect code to see there is no schema output from AIOSEOP, and AMP schema is restored.

### Test aioseop_amp_description Hook only affects meta descriptions

1. Create a child theme.
2. In the theme's file directory, edit `functions.php`.
3. Add `add_filter( 'aioseop_amp_description', '__return_false' );`
4. Inspect code to see there is no meta-description output from AIOSEOP.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by arnaudbroes** [comment]
This has been tested and can be code reviewed. I've also made sure to validate the output structured data with Google's validator tool.

**Comment by arnaudbroes** [comment]
Needs response from @EkoJR first here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2875

**Comment by EkoJR** [comment]
@semperfiwebdesign/aioseop-core-committers Currently, this PR allows `aioseop_amp_description` ( https://semperplugins.com/documentation/disable-meta-description-on-amp-pages/ ) hook to also disable the schema output. The changes related to **AMP Head unexpectedly returns when there is no AIOSEOP Description** #2875 were kept fairly simple; only changing `==` to `===`.

Do we want the filter to disable schema as well, or should I refactor it further to only effect meta description?

**Comment by wpsmort** [comment]
My opinion is that we should have a separate new filter for disabling Schema on AMP pages.  The existing filter should only disable meta descriptions on AMP pages.

**Comment by wpsmort** [comment]
@EkoJR I tested this and found two problems:

1. When you set Use Schema.org Markup to Disabled then the Schema markup output by the AMP plugin is missing.  We should only disable the AMP plugin output if Use Schema.org Markup is set to Enabled.

2. The aioseop_amp_schema flter removes the SEO meta description when it should only remove Schema markup.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
This is approved and can be merged.

**Pull request merged**
