### PR TITLE
Fix line-broken localized help link.

### PR DESCRIPTION
**Pull request by mayukojpn**
## Proposed changes

Currently help links on the next to metabox titles is overflowed when using Japanese locale. `width` attribute should be removed and accepted in any length.

screenshot_2019_01_10_8_08

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Unit tests pass with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by arnaudbroes** [comment]
This has been reproduced and the fix has been tested. @michaeltorbert needs code review.

**Comment by michaeltorbert** [comment]
@arnaudbroes Is there an issue for this?

**Comment by arnaudbroes** [comment]
> @arnaudbroes Is there an issue for this?

Yes, #2143 (has been referenced above my previous comment).

**Comment by wpsmort** [comment]
The code has been reviewed.  Ready for merge.

**Pull request merged**
