### PR TITLE
support external images

### PR DESCRIPTION
**Pull request by contactashish13**
#1264

### CODE REVIEW

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by michaeltorbert** [comment]
@contactashish13 Can you fix these conflicts?

**Comment by wpsmort** [comment]
This is tested and is ready for code review.

**Comment by michaeltorbert** [comment]
@contactashish13 Since we now no longer support >WP 4.4, we may as well use wp_parse_url()

**Comment by contactashish13** [comment]
@michaeltorbert I'm confused. I thought we were going not support anything below 4.5 and that support was going to be a major release. Is that not the case?

**Comment by arnaudbroes** [comment]
@contactashish13 I think Michael meant to say "we no longer support <WP 4.5".

**Comment by michaeltorbert** [comment]
Corrected. I had the symbol backwards. wp_parse_url came out in 4.4, we already require 4.4 as a minimum

**Comment by contactashish13** [comment]
So, just to confirm, is minimum support going to be 4.4 or 4.5? I remember discussing 4.5 with you.

**Comment by michaeltorbert** [comment]
Right now we already require a minimum of 4.4. we had parse_url instead of wp_parse_url because we used to have an older minimum requirement.

You and I discussed moving to 4.5 minimum.

**Pull request merged**
