### PR TITLE
#1035 Brackets preg_match is removed.

### PR DESCRIPTION
**Pull request by amostajo**
Issue #1035 
Line that was giving fatal and was striping bracket codes is removed.
Has been tested on local environment and one wp setup with 2.3.15 error.

### CODE REVIEW

**Comment by wpsmort** [comment]
@amostajo I am closing this PR as it affects auto generated descriptions and we must leave those alone.  Please see my last comment here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1035#issuecomment-322911772

**Comment by amostajo** [comment]
@wpsmort We need to open this again since I the change applies to what we want to accomplish with auto-generated and manually entered descriptions.

**Comment by amostajo** [comment]
@wpsmort ready for testing

**Comment by michaeltorbert** [comment]
@wpsmort See if this works and is ready to ship (pending code review). If not, let's push it out to 3.0.

**Pull request closed without merging**
