### PR TITLE
XML Sitemap Memory

### PR DESCRIPTION
**Pull request by contactashish13**
Issue #1200

### CODE REVIEW

**Comment by wpsmort** [comment]
I have tested this PR and everything works fine with the XML Sitemap module.  I confirmed that this doesn't break anything.  However, when testing on two sites I did see that this uses the same amount of memory when compared to the current version of AIOSEOP.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts with this PR

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts

**Comment by michaeltorbert** [comment]
@contactashish13  This PR seems to delete large parts of new code, for instance in aioseop_module.css (maybe more).

**Comment by contactashish13** [comment]
It seems to but if you ignore whitespace the content is the same. I didn't change this CSS so the only way I can merge is by comparing what exists in development by ignoring whitespace and then comparing what was added extra. I found that nothing was added so I just used the code from development. This and other PRs are so old that this is how some merges will have to be done.

If you have another suggestion, let me know.

**Comment by contactashish13** [comment]
@michaeltorbert I'll be merging code that I have changed and commit. Partially merged files will have to be reviewed by you and/or @EkoJR to merge changes by either of you. That seems to be the best way forward to resolve. Please let me know if you suggest another approach.

**Comment by michaeltorbert** [comment]
@contactashish13 What are partially merged files?
Also, any idea why Travisci failed?

**Comment by contactashish13** [comment]
> @contactashish13 What are partially merged files?
> Also, any idea why Travisci failed?

please ignore https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1223#issuecomment-425044656

My changes were minimal so this is how I have merged the changes now:
1. Overwrote the conflicting file with the current code in 2.9
2. Updated the code with my piecemeal changes

@michaeltorbert and @EkoJR please double check that your changes have been merged.

**Comment by michaeltorbert** [comment]
@contactashish13 This still reverts previous changes.

**Comment by contactashish13** [comment]
There is no other way of doing this in my view. Please suggest with another option.

**Comment by michaeltorbert** [comment]
@contactashish13 I recommend starting a new PR and redoing the commits for clean PR.

**Pull request closed without merging**
