### PR TITLE
Replace parse_url with wp_parse_url 

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #1614

## Proposed changes

Replace the parse_url() function with the built-in wp_parse_url() function. 

## Types of changes

- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

Have a look at the code changes and see where this function has been changed. You'll just want to check if everything still works fine, mainly the sitemap.

EDIT: in order to test if schemeless images are still being processed correctly, which is what is_image_url_valid() is meant for, follow these steps:

1. Create three new posts. 

- The first post should have an image tag with an absolute source URL such as "http://example.org/image1.jpg". 
- The second post should have an image tag with a source URL of the following format: "//example.org/image2.jpg".
- The third post should have an image tag with a source URL of the following format: "/image3.jpg".

2. Go to the XML Sitemap and make sure that each of these posts has 1 image in the sitemap.

## Further comments

I checked with Xdebug to make sure that the result is the same for each instance.

### CODE REVIEW

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by michaeltorbert** [comment]
@arnaudbroes @EkoJR Since we're using wp_parse_url, which in 4.7+ handles non-absolute URLs, do we still need to call absolutize_url() here?
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/5f119116455062cfdf11818ed11dad7ab62c1eac/modules/aioseop_sitemap.php#L4054

**Comment by arnaudbroes** [comment]
@michaeltorbert interestingly, there were some variables there that aren't being used. wp_parse_url() also wasn't needed in that function because the argument that is passed on to the function is already parsed by wp_parse_url() elsewhere, so I removed that redundant code as well.

@wpsmort can you test this again, and specifically make sure that the image indexing for our sitemap still functions correctly?

**Comment by michaeltorbert** [comment]
@arnaudbroes The specific functionality in is_image_url_valid() you changed/removed needs to be tested. Not just images in general.

**Comment by arnaudbroes** [comment]
I've added absolutize_url() back on second thought since the unit test for schemeless images is failing for one specific schemeless image URL format ( "/image.jpg") even though the image is still being included in the sitemap on fresh and existing test sites. The format fails for this function but might still be processed and picked up somewhere else in the code. The other redundant code is still removed though.

@wpsmort I'm updating the testing instructions above.

**Comment by michaeltorbert** [comment]
+1 for unit tests

**Comment by wpsmort** [comment]
This is tested and is good.

**Pull request merged**
