### PR TITLE
Remove using post_content for generating schema description

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2785

## Proposed changes

Removes generating schema description from post_content.

## Types of changes

What types of changes does your code introduce?
_Delete those that don't apply_

- Bugfix (non-breaking change which fixes an issue)
- Removing old code/functionality

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [ ] I have added necessary documentation, or have created an issue for docs (if appropriate).

## Testing instructions
1) Enable schema markup.
2) Go to a published page, and check if the Schema Description is not generated from the content.

Note: Description used the SEO Description, or if empty, the post Excerpt.

### CODE REVIEW

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
This is good and can be merged. Just curious, @EkoJR, it works for the excerpt?

**Comment by EkoJR** [comment]
Yea, it with still fall back on the excerpt if seo description is empty.

**Comment by michaeltorbert** [comment]
Are we going to have the same problem if they've used shortcodes in the excerpt? I wonder if we should just ignore both the content and the excerpt?

**Comment by michaeltorbert** [comment]
#2774

**Pull request merged**
