### PR TITLE
Shorten post content before processing description

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #3050

## Proposed changes

Fixes an issue where the Preview Snippet may hang while long posts being edited. 

## Types of changes

What types of changes does your code introduce?

- Bugfix (non-breaking change which fixes an issue)
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [ ] Travis-ci runs with no errors.

## Testing instructions

1. Install the latest version and create a long post with 25,000 or more words.
2. When you edit the content, the page should shortly hang. 
3. Install this PR and confirm this is no longer the case.

### CODE REVIEW

**Comment by wpsmort** [comment]
@arnaudbroes I'm unable to reproduce the problem by following the steps you provided.  I've done side-by-side comparison tests between this PR and the current version and can find no difference.  Can you provide more information as to how to reproduce the original bug, i.e. what settings you need in AIOSEOP and whether this happens with the block editor or classic editor.

**Comment by michaeltorbert** [comment]
I'm also unable to reproduce it.

**Comment by arnaudbroes** [comment]
Ben was able to reproduce the issue - I've now asked him to test the fix.

image

**Comment by arnaudbroes** [comment]
Ben confirmed the fix - 

image

**Comment by arnaudbroes** [comment]
@michaeltorbert I'll let you do another code review since Ben also tested it.

**Pull request merged**
