### PR TITLE
Special Characters Issue

### PR DESCRIPTION
**Pull request by contactashish13**
#1363

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 I tested this but the Home Title and Home Description fields still show the `&amp;` HTML character code instead of the & symbol.  The only way to correct this after updating to the code in this PR is to enter the Home Title and Home Description again.  This is a problem because it requires users to make a change.  

There are two things that need to happen when you update to this code:

1). The & symbol is displayed in the Home Title and Home Description fields without a user having to do anything
2). The og:title and twitter:title output in the source code is corrected from `&amp;amp;` to `&amp;`

See screenshot:

screen shot 2018-07-30 at 4 30 18 pm

**Comment by contactashish13** [comment]
@wpsmort have fixed this.

**Comment by arnaudbroes** [comment]
This is good now. Needs code review.

**Comment by michaeltorbert** [comment]
@contactashish13 What are your thoughts on using wp_specialchars_decode instead of htmlspecialchars-decode?

**Comment by wpsmort** [comment]
@contactashish13 I tested this and found that there are instances where special characters are displayed as the character instead of the HTML character.  For example, an & is displayed in the meta tag instead of `&amp;`.

The behavior of the current version of AIO is that the HTML character is output.  This PR changes that behavior.  This happens on the homepage as well as posts, pages, etc.  

Can you make sure that special characters are output in the source code as HTML.

**Comment by wpsmort** [comment]
@contactashish13 Here is the definitive list of special characters and how we currently output them in HTML source code:

Apostrophe ' - should be output as &#039;
Double quotes " - should be output as &quot;
Ampersand & - should be output as &amp;

All of the characters above are affected by this PR, i.e. the way they are output in the source code has changed.

These special characters are output as is:

Brackets [ ]
Slash /
Backslash \
Hash #  
Dollar $
Percent %
Parenthesis ( )
Asterisk *
Plus +
Comma ,
Hyphen - 
Colon : 
Semicolon ; 
Equal = 
Question ? 
At @ 
Caret ^ 
Underscore _ 
Grave ` 
Braces { } 
Pipe | 
Tilde ~ 
Exclamation ! 
Period .

These are not affected by this PR.

**Comment by contactashish13** [comment]
@wpsmort have handled all these characters. You may want to add `<` and `>` as well to the list.

**Comment by wpsmort** [comment]
This is tested and is good.  Ready for code review

**Pull request merged**
