### PR TITLE
Add Schema structural data

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #73

## Proposed changes

Add the schema.org structural data to be outputted on the frontpage.

## Types of changes

What types of changes does your code introduce?
_Delete those that don't apply_

- New feature (non-breaking change which adds functionality)
- Adds new API hooks

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code. If creating a separate issue for an item, link to the issue # at the end of the line._

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [x] I have added necessary documentation, or have created an issue for docs (if appropriate).

## Testing instructions

1. Using defaults, navigate to one of the front pages.
2. Right click and inspect to show code.
3. In the header, underneath `<!-- All in One SEO Pack ... -->`, there should be a script for ld+json.
4. Copy the data, and go to [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool).
5. Paste code and click on Validate.

To change sitewide settings.

1. Go to admin, and click on AIOSEOP > General Settings.
2. Navigate to Schema Settings, and change settings there.

## Further comments

This will still need help details added to tooltips with help from @wpsmort 

Note: I have noticed the phone number for contactPoint does require the full phone number including a country's code ( ex. +1 for US ), and given that countries use different formats, I wasn't sure if it would be wise to format it ourselves.

### CODE REVIEW

**Comment by wpsmort** [comment]
@EkoJR I have completed my initial testing and have the following comments:

1. Remove the meta box and all options from Social Meta > Social Profile Links
2. Remove duplicate JSON code for Sitelinks Searchbox output in source code
3. Format the new JSON code so the canonical link code is on a new line
4. The article markup for posts is missing the image
5. The markup for pages is missing the schema for WebPage
6. Name is missing from the author markup for posts
7. We could add sameAs in the Person markup and list the social profiles for the author (taken from their user profile)
8. datePublished and dateModified are missing from the homepage when it’s a static page
9. The Phone Number and Type of Contact fields should be hidden when Person is selected
10. WebPage url is incorrect for a post in a blog, it should be the URL for the post
11. datePublished and dateModified are missing for a post in a blog
12. Article markup is missing for a post in a blog
13. I got this notice when viewing a post and homepage is set to blog - Notice: Undefined index: aioseop_person_user in wp-content/plugins/all-in-one-seo-pack-i-73/inc/schema/graphs/graph-article.php on line 97

It's best if we have a call to discuss this so I can show you what each item above means.

**Comment by EkoJR** [comment]
@wpsmort I added the changes, but I'm unable to find an issue with 'Name is missing from the author markup for posts'.

**Comment by wpsmort** [comment]
@EkoJR I have tested again and here are my comments:

1. Blog page on a website is missing WebPage markup
2. SameAs sometimes has a comma separating links and sometimes has \r\n
3. Name is missing from the author markup in Article for posts
4. I noticed we’re outputting schema markup on custom post types, custom taxonomies and media attachment pages

Here's the markup I see for 3 above where the name is missing from the author markup - 

```
"@type": "Article",
		"@id": "https://wordpress-138706-916931.cloudwaysapps.com/hello-world/#article",
		"isPartOf": {
			"@id": "https://wordpress-138706-916931.cloudwaysapps.com/hello-world/#webpage"
		},
		"author": {
			"@id": "https://wordpress-138706-916931.cloudwaysapps.com/#author"
		},
		"headline": "Hello world!",
		"datePublished": "2019-07-10T14:58:14+00:00",
		"dateModified": "2019-07-11T15:42:16+00:00",
		"commentCount": "1",
		"mainEntityOfPage": {
			"@id": "https://wordpress-138706-916931.cloudwaysapps.com/hello-world/#webpage"
		},
		"publisher": {
			"@id": "https://wordpress-138706-916931.cloudwaysapps.com/#person"
		},
		"articleSection": "Uncategorized",
		"image": {
			"@type": "ImageObject",
			"@id": "https://wordpress-138706-916931.cloudwaysapps.com/hello-world/#primaryimage",
			"url": "https://wordpress-138706-916931.cloudwaysapps.com/wp-content/uploads/2019/07/SF01.jpg"
		}
```

**Comment by EkoJR** [comment]
I found some issues with person, which was causing a conflict with a site representing a person where some data structure values required an organization data type, and also wasn't outputting the correct author data for articles. So I had to refactor a site representing person into organization.


3. That is because 'name' is in the Person markup, which is what the '@id' in author references to. Which seemed to have been bugged earlier (mentioned above).
```
"@type": "Person",
"@id": "http://aioseop.test/author/admin/#author",
"name": "Admin",
"sameAs": ["facebook.com", "twitter.com"],
"image": {
	"@type": "ImageObject",
	"@id": "http://aioseop.test/#personlogo",
	"url": "http://2.gravatar.com/avatar/8a28960fb53c9b0d4c7a02410b5fb078?s=96&d=mm&r=g",
	"caption": "Admin"
}

```

**Comment by wpsmort** [comment]
@EkoJR There are a couple of new bugs as follows:

1. The URLs in sameAs are no longer separated by anything so they appear as below.  This only happens when you select Organization.  If you select Person then the URLs are separated with a comma so it's specifically where you removed the \r\n that this is happening.

`"sameAs": ["https://www.facebook.com/aioseopack/https://twitter.com/aioseopack"],`

2. When you select Person, the type is output as below. I believe this is what you're referring to above so we should discuss this and decide on what approach we want to take. 

`"@type": ["Person", "Organization"],`

3. Name is missing from the author markup in Article for posts.  This field is required, without it the Structured Data Testing Tool returns an error.

4. I see you're now outputting `"caption": false` when no image caption exists.  Is there a reason for this?

**Comment by wpsmort** [comment]
@EkoJR I have some changes as follows:

1. We should hide all of the options in the Schema Settings section when Use Schema.org Markup is unchecked.  In fact, we should probably change the Use Schema.org Markup option to a radial with two options - Enabled and Disabled.  This would be in line with similar settings in the plugin.

2. We should not make users enter a plus sign in the Phone Number field.  We should output the plus for them  Also, can we use input masking or some other method to make entering the phone number more intuitive so users are required to enter their country code.  I found this article - https://uxmovement.com/forms/bad-practices-on-phone-number-form-fields/

3. The static Blog page is using the Site Title as the name.  Whereas the static Home page is using the page title as the name.  I think we should change it so that both use the page title but we make it filterable.

Let me know if you have any questions.

**Comment by EkoJR** [comment]
Example of modifying schema data to modify the title/name.

```
if ( ! function_exists( 'prefix_schema_webpage_static_page_title' ) ) {
	/**
	 * Filter for Schema WebPage Object to Change Title/Name
	 *
	 * @param array  Dynamically generated data through inherited schema graphs.
	 * @param string Current schema (child) class being used to prepare data.
	 * @return array
	 */
	function prefix_schema_webpage_static_page_title( $data, $schema_class ) {
		// Skip if we're not handling data for WebPage schema object.
//		if ( 'AIOSEOP_Graph_WebPage' !== $schema_class ) {
//			return $data;
//		}

		global $wp_query;

		if ( is_front_page() && is_page() ) {
			// Static page - Homepage.

			// Get the post/page title & site title.
			$data['name'] = get_the_title() . ' | ' . get_bloginfo( 'name' );
		} elseif ( is_home() && $wp_query->is_posts_page ) {
			// Static page - Posts page.

			// Get the site title.
			$data['name'] = get_bloginfo( 'name' );
		}

		return $data;
	}
	add_filter( 'aioseop_schema_class_data_AIOSEOP_Graph_WebPage', 'prefix_schema_webpage_static_page_title', 10, 2 );
}
```

**Comment by EkoJR** [comment]
For adding CPT support

```
if ( ! function_exists( 'prefix_schema_layout_custom_post_types' ) ) {
	/**
	 * @param array $layout
	 * @return array
	 */
	function prefix_schema_layout_custom_post_types( $layout ) {

		if ( is_archive() ) {
			if ( is_tax() ) {
				$layout = array(
					'@context' => 'https://schema.org',
					'@graph'   => array(
						'[aioseop_schema_Organization]',
						'[aioseop_schema_WebSite]',
						'[aioseop_schema_CollectionPage]'
					),
				);
			}
		} elseif ( is_singular() || is_single() ) {
			global $post;

			if ( in_array( get_post_type( $post ), array( 'CUSTOM_POST_TYPE_SLUG' ) ) ) {
				$layout = array(
					'@context' => 'https://schema.org',
					'@graph'   => array(
						'[aioseop_schema_Organization]',
						'[aioseop_schema_WebSite]',
						'[aioseop_schema_CollectionPage]'
					),
				);

				array_push( $layout['@graph'], '[aioseop_schema_WebPage]' );
				if ( ! is_post_type_hierarchical( $post->post_type ) ) {
					array_push( $layout['@graph'], '[aioseop_schema_Article]' );
					array_push( $layout['@graph'], '[aioseop_schema_Person]' );
				}

			}
		}

		return $layout;
	}
	add_filter( 'aioseop_schema_layout', 'prefix_schema_layout_custom_post_types' );
}
```

**Comment by wpsmort** [comment]
@EkoJR I tested this and have the following comments:

1. If I set Use Schema.org Markup to Disabled, it no longer removes the schema markup from the source code of my site.  This was working in previous commits.

2. The static Blog page is now using the post title from the latest post, can you change this to use the page title please.

3. When I install the PR code on an existing site that is running the current version of the plugin, and where the Social Profile Links section in the Social Meta module has been configured, then I get these notices:

PHP Notice:  Undefined index: aiosp_site_represents in all-in-one-seo-pack-i-73/inc/schema/graphs/graph-organization.php on line 59
PHP Notice:  Undefined index: aiosp_organization_name in all-in-one-seo-pack-i-73/inc/schema/graphs/graph-organization.php on line 75
PHP Notice:  Undefined index: aiosp_site_represents in all-in-one-seo-pack-i-73/inc/schema/graphs/graph-website.php on line 59
PHP Notice:  Undefined index: aiosp_site_represents in all-in-one-seo-pack-i-73/inc/schema/graphs/graph-webpage.php on line 142

**Comment by wpsmort** [comment]
This is tested and is good.

**Pull request merged**
