### PR TITLE
Cleanup Sitemap with WPCS

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2059

No changes in operations; TODOs were added instead. This was to inspect the sitemap code, and find any potential issues through code sniffing.

TODOs added...
* Fix undefined variables.
* Add esc_* functions.
* Change `parse_url()` to `wp_parse_url()`.
* Add 'true' in 3rd arg with `in_array()`.
* Add nonce verification.
* Add/Change `$_POST` to `filter_input()`.
* Change `urlencode()` to `rawurlencode()`.

### CODE REVIEW

**Comment by wpsmort** [comment]
@EkoJR I tested this and found one problem:

The Excluded Pages option doesn't work when you enter a post ID.  It does work if you enter a slug.  For example, if I enter post ID 2 then this post is still included in the sitemap.  But if I enter the slug hello-world then the post is excluded.

**Comment by EkoJR** [comment]
@wpsmort It looks like changing the hardcoded numberic check to a strict comparison was the problem. Should be good now.

**Comment by wpsmort** [comment]
This is tested and is good.  Ready for code review.

**Comment by EkoJR** [comment]
Closed to rebase #2084

**Pull request closed without merging**
