### PR TITLE
#943 - Fix for shortcode and brackets.

### PR DESCRIPTION
**Pull request by amostajo**
Issue #943 

Always runs `do_shortcode` on descriptions, shortcodes on titles are
removed and fixes bracket instances.

### CODE REVIEW

**Comment by wpsmort** [comment]
@amostajo I found one issue when testing this.  The auto generated OG description placeholder text displays the shortcodes.  See screenshot.

screen shot 2017-08-02 at 8 13 05 pm

**Comment by amostajo** [comment]
@wpsmort placeholder fixed.

**Comment by wpsmort** [comment]
This looks good but I'll do more testing in the morning.

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is good.  Based on the code in this PR, I believe we can now remove all of the Run Shortcodes options.  I'll open a separate issue for this.

**Pull request merged**
