### PR TITLE
Remove version check for Gutenberg/Chrome compatibility fix and check if user agent is set

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #2914 & #2952

## Proposed changes

Removes the version check for the Gutenberg/Chrome compatibility fix since the Gutenberg team decided not to implement a fix of their own.

## Types of changes

- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

Use a Chromium v77 browse and reproduce the issue; then install this PR and make sure the fix still works.

### CODE REVIEW

**Comment by michaeltorbert** [comment]
Testing complete.

**Comment by arnaudbroes** [comment]
@EkoJR can you review this and let me know what comments you have?

**Comment by EkoJR** [comment]
@arnaudbroes the only problem that I've found is the filename which is part of the compat class structure. Otherwise, it looks alright.

**Comment by arnaudbroes** [comment]
I've added an `isset( $_SERVER['HTTP_USER_AGENT'] )` to fix #2952 in this PR as well.

**Comment by arnaudbroes** [comment]
@ekojr please review this again.

**Pull request merged**
