### PR TITLE
Fix noindex for paginated content

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #2797

## Proposed changes

Fix an issue where noindex for paginated pages doesn't affect the homepage and other archive pages.

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [ ] Travis-ci runs with no errors.

## Testing instructions

Make sure that the "Noindex paginated pages/posts" setting does not affect the first page of the homepage, but does affect page 2 and onward. Same goes for the static posts page and other pages.

### CODE REVIEW

**Comment by wpsmort** [comment]
@arnaudbroes This works great for the homepage but needs to also work for the static Posts page.  

If you set a static home page and a static posts page then the Noindex / Nofollow paginated pages needs to be output on page 2 and higher of the posts (Blog) page.

**Comment by arnaudbroes** [comment]
@wpsmort I had a look at v3.1.1 as discussed and noticed that "noindex for paginated posts/pages" seemed to affect paginated content everywhere so I just went with that. That might not have been the intended behaviour (although I also went back a few more versions to see if anything was different) but that's how it used to be. We might want to consider renaming that setting to "noindex for paginated content" though.

**Comment by wpsmort** [comment]
@arnaudbroes There's a typo on line 4643, you used 'aiosp_paginated_nofollow' for the noindex option.

**Comment by wpsmort** [comment]
This is tested and is good.  I fixed an error in the code where nofollow was incorrectly used for noindex.

**Pull request merged**
