### PR TITLE
Fix undefined index in aioseop_class.php

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2096

### CODE REVIEW

**Comment by wpsmort** [comment]
This is tested.  I'm also not able to reproduce the PHP notice reported in the issue.  However, I've tested all variations of the Content Type Settings and Display Settings and they all work.  I've tested on PHP 5.2 to 7.2.

Ready for code review.

Ready for code review.

**Comment by michaeltorbert** [comment]
I'm not comfortable pushing a possible fix that we can't test. I've reached out to the user to verify the fix works.

**Comment by michaeltorbert** [comment]
The user has tested and confirmed the fix.

**Comment by michaeltorbert** [comment]
The user reported this fixed #2097 also.

**Pull request merged**
