### PR TITLE
Apply filters to the Person schema's array of data

### LINKED ISSUE #2962: Schema.org - Add filter for custom Person markup
We'd like to add a `jobTitle` to the `Person` structured data that's being generated by the All In One SEO pack.

At a glance, it looks like the fields are hardcoded and don't allow for any modification. Here are lines 64-70 of `wp-content/plugins/all-in-one-seo-pack/inc/schema/graphs/graph-person.php`:

```
$rtn_data = array(
	'@type'  => $this->slug,
	'@id'    => $author_url . '#' . $hashtag,
	'name'   => $author_name,
	'sameAs' => $this-> get_user_social_profile_links( $user_id )
);
```

If I modify that code to be:

```
$rtn_data = array(
	'@type'  => $this->slug,
	'@id'    => $author_url . '#' . $hashtag,
	'name'   => $author_name,
	'sameAs' => $this-> get_user_social_profile_links( $user_id ),
	'jobTitle' => 'Job title goes here'
);
```

Then it outputs exactly what we want it to, albeit with placeholder info.

A more proper way to do it would be to apply a filter, which would allow you to modify the array data as needed:

```
$rtn_data = array(
	'@type'  => $this->slug,
	'@id'    => $author_url . '#' . $hashtag,
	'name'   => $author_name,
	'sameAs' => $this-> get_user_social_profile_links( $user_id )
);
		
$rtn_data = apply_filters('aioseop_person_data', $rtn_data);
```

By doing that, I can now modify the array data from my `functions.php` file:

```
function addAuthorJobTitle($person_data)
{
	$person_data["jobTitle"] = "Job title goes here";
	return $person_data;
}

add_filter('aioseop_person_data', 'addAuthorJobTitle');
```

### PR DESCRIPTION
**Pull request by Pikamander2**
Apply filters to the Person schema's array of data, allowing users to modify the schema output from their functions.php file as needed.

Resolves #2962

## Types of changes

What types of changes does your code introduce?
- New feature (non-breaking change which adds functionality)
- Adds new API hooks
- Improves existing functionality
- Improves existing code

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code. If creating a separate issue for an item, link to the issue # at the end of the line._

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [ ] Travis-ci runs with no errors.

### CODE REVIEW

**Comment by arnaudbroes** [comment]
Steve tested this and said it is good.

**Comment by EkoJR** [comment]
This is already possible, and is a duplicate of `aioseop_schema_class_data_{CLASS NAME}`.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/8c85891893863c38a5b37e14077cc50499192b01/inc/schema/graphs/graph.php#L151

```
function prefix_aioseop_schema_person( $data ) {
	$data['jobTitle'] = 'Job title goes here';

	return $data;
}
add_filter( 'aioseop_schema_class_data_AIOSEOP_Graph_Person', 'prefix_aioseop_schema_person' );
```

**Comment by wpsmort** [comment]
I have confirmed this duplicates an existing filter so I'm closing this PR.

**Comment by arnaudbroes** [comment]
I've deleted the relevant documentation as well.

**Pull request closed without merging**
