### PR TITLE
Fix aioseop_notice not loading database for users w/o 'aiosp_manage_seo' capabilities

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2556

## Proposed changes

Fixes aioseop_notices not loading database values with non-admins (users without `aiosp_manage_seo` capabilities), and causing the notices to reset when non-admin users browsed wp-admin.

## Types of changes

What types of changes does your code introduce?

- Bugfix (non-breaking change which fixes an issue)
- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [ ] I have added necessary documentation, or have created an issue for docs (if appropriate).

## Testing instructions
This will need 2 users. 1 as the main admin, the other as an Editor.

1. Go to Settings > Reading and enable "Discourage search engines from indexing this site" to trigger `blog_public_disabled`.
2. Browse admin as the site admin to set WC notice.
3. With notice displayed, click 'No thanks' to delay notice.
4. In a different browser (or log out and log in as editor), browse site as an Editor. (the bug would trigger a reset)
5. Go back other user, and browse as site admin. Notice should not appear.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by michaeltorbert** [comment]
Won’t this make it show up for non-admins?

**Comment by michaeltorbert** [comment]
What specifically does “deactivate the notice” mean? Reset it if it was dismissed?

**Comment by EkoJR** [comment]
> Won’t this make it show up for non-admins?

No, this will not show up for admins. However, the conditions of the site environment should trigger (de)activate.

> What specifically does “deactivate the notice” mean? Reset it if it was dismissed?

No, deactivate just removes it from the active_notices => display_time. If it is dismissed, it stays dismissed. (Re)activating a notice that has not been dismissed will reset the active_notice => display_time. It was done in this manner to prevent notices with a set delay time from using the old display time and potentially displaying immediately rather than the intended delay time.

**Comment by wpsmort** [comment]
@EkoJR Grunt shows there are 2 errors for this PR.

**Comment by EkoJR** [comment]
Current grunt changes are unrelated to this PR

**Comment by EkoJR** [comment]
@michaeltorbert This isn't isolated to WooCommerce

**Comment by wpsmort** [comment]
This is tested and is good.  I was able to reproduce the bug and by following the same steps, verify that this PR fixes it.

**Comment by michaeltorbert** [comment]
@EkoJR @wpsmort Remember when checking the boxes to check what you're doing as well. This was pulled against master.
During testing, always do a double check.

**Pull request merged**
