### PR TITLE
#1022 Enable `Never Shorten Long Descriptions`

### PR DESCRIPTION
**Pull request by amostajo**
Issue #1022

Make existing setting `Never Shorten Long Descriptions` functional.

### CODE REVIEW

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is ready for code review.

**Comment by michaeltorbert** [comment]
@amostajo With your change, would you say we definitely don't need this? https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L2451

**Comment by amostajo** [comment]
@michaeltorbert Not sure. I might have to do some testing and check when is that line called.

**Comment by amostajo** [comment]
@michaeltorbert #951 has modified the way truncate works, the changes applied there make this PR unnecessary.

**Pull request closed without merging**
