### PR TITLE
Google Search Console validation error in 2.4.1.1

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@contactashish13 Is this for #1250?

**Comment by contactashish13** [comment]
@michaeltorbert yes

**Comment by wpsmort** [comment]
@contactashish13 Please confirm that this PR is replaced by #1256 and we'll close this PR.

**Comment by michaeltorbert** [comment]
@wpsmort This is the same as 1256, with the addition of htmlspecialchars in that one.

**Pull request closed without merging**
