### PR TITLE
Revert Sitemap add title & caption for images Issue-1753 PR-1907

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2008 ~~#2011 (duplicate)~~

This reverts PR #1907

With my environment, I was getting the following time/memory; using xDebug Profiler Enabled & QCacheGrind.

| Branch        | Time Cost          | Memory Cost |
| ------------- |:-------------:| -----:|
| Master      | 116,053,444 | 939,026,568 |
| i-2011 (This PR)      | 70,269,334      |   684,063,000 |

### CODE REVIEW

**Comment by wpsmort** [comment]
@EkoJR I tested this PR on the site where I can reliably reproduce the memory issue with static XML sitemaps and I got this error when trying to generate the sitemap by clicking the Update button:

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /wp-content/plugins/all-in-one-seo-pack-2011/modules/aioseop_sitemap.php on line 3085

However, please note that I did the same test with AIOSEOP v2.8 and got the same result but with this error:

PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /wp-includes/taxonomy.php on line 0

I think we have to consider either getting rid of static sitemaps or enabling sitemap indexes by default, as per my comments here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2008#issue-373697660

**Comment by EkoJR** [comment]
@wpsmort with Maximum Execution Time, it's going to be quite difficult to nail it down any further unless optimization becomes a key focus, especially while scanning. With the bigger CPU/Memory heaps gone, it's probably going to become more random with what error stack trace is returned. Right now, that error just points to a simple `if` statement. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/996ae09c41aa66a14ac9ab744d780d9046a9f683/modules/aioseop_sitemap.php#L3085

30 seconds is a bit low, but when running a site it is considered ideal to keep load times low.

**Comment by michaeltorbert** [comment]
@wpsmort @EkoJR  Does this issue get resolved if we remove static sitemaps and and enable indexes?

**Comment by EkoJR** [comment]
@michaeltorbert I believe the issue still can occur when creating the static sitemap; which could prevent the sitemap from being created. However, if an admin can get past the memory heap, then it would avoid continuous crashes, but then there's concern when content is added/updated.

**Comment by EkoJR** [comment]
Closing this in favor of #2051

**Pull request closed without merging**
