### PR TITLE
Fix PHP Warning on Page Editor #1491

### PR DESCRIPTION
**Pull request by EkoJr**
Fix PHP Warning on Page Editor #1491

Created a new PR in favor of, instead of PR #1520.

### CODE REVIEW

**Comment by wpsmort** [comment]
This PR has been tested. I reproduced the warning in PHP 7.2 and confirmed this fixes it.   This is ready for code review.

**Comment by wpsmort** [comment]
The correct PR for this is #1522

**Comment by contactashish13** [comment]
@EkoJr A few comments/suggestions on the test case:

- the class name seems to be clunky and maybe not in the right case?`All_in_One_SEO_Pack_Test_aiosp_mrt_get_url `

- https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1522/commits/4c2dbd113e2c4046abd97980e48bd969c7ceedcd#diff-a7d32a5404240c8dfddfb717726e1183R79 has been defined in the base class. You can use that or modify it accordingly so that the base class becomes more useful and generic.

- The class should preferably inherit the base class. You can modify the base class for the setup/teardown methods as it will be useful for all other tests too. 

- can you review the phpdoc comments as some seem out of place? e.g. https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1522/commits/8a0a9a4c57d998b674aea4ffad5afcff9581428c#diff-41fde5a00d3cd8f77c1c24d21c445c29R120

- can you also follow the same folder structure that we had discussed viz. `tests/<module>/test-<specfic>.php`?

- I don't know if its valid or not, but do you also want to test with the following combinations?
a) pretty permalinks on
b) category urls
c) tag urls
d) custom post type urls

- Can you also sync with master so that the tests fire when you create a PR?

**Comment by EkoJr** [comment]
@contactashish13

1. It's a WordPress Standard to name classes by the method you are testing. Although I forgot to add Camelcase for the method name ( https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#test-classes ). I also had to extended to WP_UnitTestCase because I needed a testcase, and wasn't part of the sitemap module/class.
2. At the time, I had mentioned in a conversation I couldn't use it since I needed a setup specific to a test and isolated, but since then you added changes, and extending it would make it more generic and useful in the future.
3. I did try to follow similar naming to keep it relatively consistent. I have been a bit hesitant to add anything to the base class though until I see more commonalities, and possibly diverse implementations. Also, at the time I was just trying to get a setup function that I could get an overall view of to understand.
4. Probably, there wasn't much info from WP, how would you suggest the order/placement?
5. Yea, we had discussed the file structure, and I'm still unsure about the file structure that you were using. I was explaining how I was trying to follow WP's structure ( without violating its own standards in naming files...ironically ) ( https://github.com/WordPress/wordpress-develop/tree/master/tests ). We had agreed to exclude `phpunit` as a folder inside of `tests`, but inside the `phpunit` folder would be the ideal structure, and may explain the extra `tests` folder.
6. I could double check, but I believe the method was used just for posts/pages. Pretty urls might affect it though.
7. Yea, I can Rebase, but it usually ends up creating new commits and I believe GitHub made it easier to rebase on merge for Repo Admins.

One important point that I have found. These tests are intended to be isolated. With a testcase class to extend to (base class), it would be intended to assist with the test class. Shared testing I'm not too sure about though.

WP & PHPUnit also seems to focus on class/method & function testing, but with globals, files, or single instances I did notice others mention it as a common conflict with testing multiple instances. In this case though, I focused on the method that was the problem.

**Comment by EkoJr** [comment]
6. Looking at it now, you are correct. There are other instances that could be tested for that method. I believe this was one of the first PRs I was using to get my feet wet with PHPUnit, and focused on the failed test case.

**Comment by EkoJr** [comment]
Closing in favor of #1588

**Pull request closed without merging**
