### PR TITLE
Fix meta box help icon alignment

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #1956

## Proposed changes

Fixes an issue where a help icon in the meta box is pushed back from the right side when the social meta module is enabled.

## Types of changes

What types of changes does your code introduce?

- Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions

Enable the Social Meta module and make sure that the top help icon (right next to the "Upgrade to Pro" link) is aligned properly.

## Further comments

None.

### CODE REVIEW

**Comment by wpsmort** [comment]
@arnaudbroes There's a margin-left: 64px; that needs removing from the RTL stylesheet (https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/804bc74dd2b6a5c2fe52b2bb8d7c21bb39a8476e/css/modules/aioseop_module-rtl.css#L38).  That should tidy up the alignment for RTL.  If you can make that change and test in browsers on Windows then assign back to me so I can check on Mac.

**Comment by arnaudbroes** [comment]
@wpsmort that fixes it for all browsers on Windows.

**Comment by wpsmort** [comment]
@arnaudbroes Can you resolve the merge conflicts here please.

**Comment by arnaudbroes** [comment]
@wpsmort merge conflict has been resolved.

**Comment by arnaudbroes** [comment]
@wpsmort second merge conflict has been resolved.

**Comment by wpsmort** [comment]
This is tested and is good.

**Pull request merged**
