### PR TITLE
Social Meta module - Incorrect default Object Type for taxonomies

### PR DESCRIPTION
**Pull request by contactashish13**
https://github.com/semperfiwebdesign/aioseop-pro/issues/321

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and assign to me for testing.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and assign to me for testing.

**Comment by wpsmort** [comment]
@contactashish13 I tested this on a brand new install of WordPress and the defaults were still incorrect.  I followed the steps here - https://github.com/semperfiwebdesign/aioseop-pro/issues/321#issue-249160711

**Comment by contactashish13** [comment]
@wpsmort Can you please review the steps here https://github.com/semperfiwebdesign/aioseop-pro/issues/321#issue-249160711? I am unable to see the `og:type` in the source code even if I reset all options.

It would be much easier to reproduce this and fix on my dev, which I currently cannot.

**Comment by contactashish13** [comment]
@wpsmort these steps here https://github.com/semperfiwebdesign/aioseop-pro/issues/321#issue-249160711 dont work for me at all - not on a brand new site with absolutely no dirty data and not on an old site with reset options. I am trying this with the free version.

**Comment by wpsmort** [comment]
@contactashish13 I've set up a test site on poopy for you and sent you the information via Slack.

**Comment by michaeltorbert** [comment]
> I've set up a test site on poopy for you

@wpsmort Sounds pretty crappy.

**Comment by contactashish13** [comment]
@wpsmort I created a new category and when I view it, no meta tags appear in the source - http://sincere-yacare.w5.poopy.life/category/blah/. This is the exact behavior I see on my dev site as well (https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1873/#issuecomment-430913424). I can see the og:type only for the default `uncategorized' category but not for any new category I create.

**Comment by wpsmort** [comment]
@contactashish13 The reason you weren't seeing anything in the source code was because your new category was empty.  I added a post to your new category and now it shows the OG meta with the incorrect og:type.  See screenshot below.  You'll also see that when you edit that category the Facebook Object Type drop down shows Activity.  Both the drop down and the source code should show Article.

screen shot 2018-12-29 at 1 14 45 pm

**Comment by contactashish13** [comment]
@wpsmort the poopy instance expired and I created a new one with this branch. That does not show og:type for any category even if it has posts. I'm not sure we are following exactly the same steps. It is quite incomprehensible that no matter what instance I choose, I am unable to get og:type in the view source. Please review the steps and also the steps to install the plugin - which branch etc?

**Comment by wpsmort** [comment]
@contactashish13 I created a new poopy install for you, followed the steps to recreate and the og:type is present in the source code.  I've sent you the details of the poopy install via Slack.

**Comment by contactashish13** [comment]
@wpsmort have fixed this.

**Comment by wpsmort** [comment]
@contactashish13 I tested this and it works great except for one problem.  On a brand new site, the og:type is correctly set to article in the source code of a category or tag.  However, when you edit the category or tag, Object Type drop down is set to Activity.  

Can you confirm this and fix it please.

**Comment by contactashish13** [comment]
@wpsmort All taxonomy terms created **before** activation of the module are updated with the correct object type when the module is activated. I believe the problem you have reported occurs when you create a new taxonomy term **after** you have activated the module. Have addressed this.

**Comment by contactashish13** [comment]
@wpsmort I have tested with the poopy instance you had shared on slack and it works for me. Maybe it worked after a few tries but I did not change any part of the code except for adding debug commands and activating/deactivating multiple times. Can you please test with the same poopy instance and then with a new one and try activating the module multiple times?

**Comment by wpsmort** [comment]
@contactashish13 This only happens on a brand new site on the very the first activation of the Social Meta module.  If I test on the same poopy install by resetting ALL settings to default in AIOSEOP and then activating the Social Meta module then the Object Type is correct.

**Comment by contactashish13** [comment]
@wpsmort have fixed this.

**Comment by wpsmort** [comment]
@contactashish13 I tested this and found one problem as follows:

Custom taxonomies don't have an og:type set in the source code.  Here's the steps to reproduce this:

1. Create a new site
2. Create a custom post type and custom taxonomy
3. Create a term in the custom taxonomy and then add a post to the term
4. Install this PR merged with the master branch of Pro
5. Activate the Social Meta module
6. Go to All in One > General Settings > Content Type Settings and check the box for the CPT and the box for the custom taxonomy
7. Go to All in One > Social Meta > Facebook Settings and and check the box for the CPT and set an Object Type for the post type
8. View the source code of your taxonomy term, it should show the OG meta but no og:type
9. Edit the taxonomy term and you should see the Facebook Object Type is set correctly

The og:type only gets set when you edit the term and click Update. 

**Notes:** 
- This problem only happens with custom taxonomies.  Everything works fine for the built-in taxonomies. 
- This happens on a new site or on an existing site when updating from the current version of Pro to this PR.

**Comment by contactashish13** [comment]
@wpsmort I've fixed this.

@michaeltorbert currently it is not possible to create unit tests for such changes because of how one has to "manipulate" the code to create a pro plugin. Therefore we need to consider merging pro and free to enable better unit testing coverage.

**Pull request merged**
