### PR TITLE
Social Meta Module - OG Image not pulling in full size image

### PR DESCRIPTION
**Pull request by contactashish13**
#260

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@contactashish13 Can you resolve the merge conflicts?

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and assign back to me for testing.

**Comment by wpsmort** [comment]
@contactashish13 As discussed, this is not working for me on the test site I shared with you.  If I select either Featured Image or First Attached image then the image output in the source code is the large size, not the full size image.

**Comment by contactashish13** [comment]
@wpsmort have fixed this.

**Comment by wpsmort** [comment]
@contactashish13 I tested this with each of the options under Social Meta > Image Settings > Select OG:Image Source and they all work fine except First Image in Content.  If I select this then the og:image tag uses the 150x150 thumbnail instead of the full size image.  

Can you check and rectify this please.

**Comment by contactashish13** [comment]
@wpsmort fixed.

**Comment by wpsmort** [comment]
This is tested and is good.  Ready for code review.

**Pull request merged**
