### PR TITLE
Fix conflict between Chromium v77.0.3865.75 and Gutenberg

### PR DESCRIPTION
**Pull request by arnaudbroes**
Issue #2914

## Proposed changes

Fixes a conflict between Chromium browsers and the Gutenberg editor that causes meta boxes to overlap with the content.

The PR also includes Grunt fixes which are needed for 3.2.8; else Travis CI will fail.

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [ ] Travis-ci runs with no errors.

## Testing instructions

Install a browser based on Chromium v77.0.3865.75 as well as All in One SEO Pack from WordPress.org. You'll notice that our meta box overlaps with the content. Next, install this PR and confirm that it fixed this.

## Further comments

While this isn't an issue we caused, users thinks we did, so that's why we're adding this fix.

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@arnaudbroes When was this bug introduced? WP 5.2?
Should version_compare() be 5.2 < x < 5.3, assuming it's fixed in 5.3?

**Comment by arnaudbroes** [comment]
> @arnaudbroes When was this bug introduced? WP 5.2?
> Should version_compare() be 5.2 < x < 5.3, assuming it's fixed in 5.3?

No, because it wasn't introduced in Gutenberg; it's a Chromium issue. So what we'll want to keep track of is whether Gutenberg will still include a fix for this in 5.3 now that Chromium fixed this on their end.

**Comment by michaeltorbert** [comment]
@arnaudbroes Ok I'll rephrase. Does this bug affect WP < 5.2?

**Comment by arnaudbroes** [comment]
> @arnaudbroes Ok I'll rephrase. Does this bug affect WP < 5.2?

Yes it does.

**Comment by michaeltorbert** [comment]
@arnaudbroes Then it should be checking for WP < 5.3 (assuming WP fixes it then).

**Comment by michaeltorbert** [comment]
I've tested this on WP 5.0 and 5.3. After confirming the bug on each, have confirmed the fix on each as well.

**Pull request merged**
