### PR TITLE
Updating large sitemap locks out WP-API

### PR DESCRIPTION
**Pull request by contactashish13**
#2160

### CODE REVIEW

**Comment by contactashish13** [comment]
This can be tested using the postman plugin: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en and using the update method https://developer.wordpress.org/rest-api/reference/posts/#update-a-post

**Comment by wpsmort** [comment]
@contactashish13 I'm going to need more information on how to test this as I've never used Postman or the WP API before.

**Comment by wpsmort** [comment]
I've requested some additional information from the customer who reported this in the Pro forums.

**Comment by arnaudbroes** [comment]
I tested this and can confirm this PR fixes the issue. 

In case anyone wants to reproduce the behaviour this PR fixes:

1. Install Postman or any other application/plugin to do API requests
2. Install the Basic Auth plugin on your test site - https://github.com/WP-API/Basic-Auth
3. Disable Dynamic Sitemap Generation in the XML Sitemap module
4. Add a Basic Auth token to the API request by filling in your username and credentials in the app
5. Send a POST request to yourdomainname.com/wp-json/v2/posts

You'll notice that the API does not return a response and that this PR fixes the issue.

**Pull request merged**
