### PR TITLE
Robots.txt - Add an Edit Rule feature #1820

### PR DESCRIPTION
**Pull request by contactashish13**
#1820

### CODE REVIEW

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is ready for code review.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflict with this PR.

**Comment by wpsmort** [comment]
@contactashish13 I tested this and only found one problem which is specific to multisite networks.  

If I edit a rule on a sub-site in the network and through my editing I try to override a rule at the Network Admin level then I get the correct warning but then the rule I am editing is deleted from my sub-site.

Here are the steps to reproduce:
1. Create two different rules one at the Network Admin level and one on a sub site.  
2. Edit the rule on the sub site and try to override the network admin rule
3. When you click the Modify Rule button you should see a warning the the "Rule cannot be overridden" and the rule you're editing should disappear from the screen and the database.

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is good.  It works on single and Multisite.  It is ready for code review.

**Comment by michaeltorbert** [comment]
#1820

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflicts and assign back to me for testing.

**Comment by wpsmort** [comment]
This is tested on single site and multisite.  Ready for code review.

**Pull request merged**
