### PR TITLE
Uploaded to this post dropdown (images) disappeared #1899

### PR DESCRIPTION
**Pull request by contactashish13**
#1899 (Edited to add issue -Michael Torbert)

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@contactashish13 @EkoJR What's the status of this? Ready for testing and code review?

**Comment by contactashish13** [comment]
@michaeltorbert sorry, this must have fallen off the radar somehow. I have assigned the issue to @wpsmort for testing.

**Comment by EkoJR** [comment]
I didn't notice Ashish's commit either...at the time, I had just finished a related PR and was looking for an issue to tackle, then I noticed issue #1899 was related.

The problem was with `wp_enqueue_media()` in `\All_in_One_SEO_Pack_Module::admin_enqueue_scripts`, but the proper enqueue is already handled in  `\All_in_One_SEO_Pack_Module::enqueue_scripts`. So the problem then became an issue with the instance being used; which is usually determined whether the hook was added or not. Which was then traced back to when a hook is added, however the "style" enqueue was still needed for the menu icon fix.

So, technically as an example, if you remove wp_media_enqueue() in `\All_in_One_SEO_Pack_Module::admin_enqueue_scripts` it would work properly since the next hook `enqueue_scripts` has the proper handling for it, and is for the intended screen instances as well.

Ashish's PR does solve the issue, but it just patches an issue I introduced, and might be better to reduce than add to it (also avoids creating duplicates). ...but PR #1935 is set for 2.9 as well.

**Comment by michaeltorbert** [comment]
Closing since #1935 also fixes the issue.

**Pull request closed without merging**
