### PR TITLE
Full size image for sitemap

### PR DESCRIPTION
**Pull request by contactashish13**
#1202

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 I tested this and it still pulls the image that was embedded in the post at the size that was selected, not the full size image.  See screenshot which shows the thumbnail, medium and large sizes I embedded:

screen shot 2018-03-22 at 3 23 11 pm

**Comment by wpsmort** [comment]
@contactashish13 I tested this and it works.  However, it adds an empty <image:caption> tag to a lot of the images which was not present before.  I think this may be caused by this commit - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1350/commits/66c5e51c0245f1d64305d99e209be153c0269730

**Comment by contactashish13** [comment]
@wpsmort if the caption/title is empty, it will output an empty caption/title. This behavior seems to be valid according to https://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd

**Comment by wpsmort** [comment]
This is tested and ready for code review.

**Pull request merged**
