### PR TITLE
Custom posts bbPress not outputting tags in source code

### PR DESCRIPTION
**Pull request by contactashish13**
#1297

### CODE REVIEW

**Comment by wpsmort** [comment]
@contactashish13 I tested this PR and it is outputting the SEO meta except it's missing meta keywords and canonical URL.  Can you look into why those two tags don't get output.

**Comment by wpsmort** [comment]
@contactashish13 I've set upa test site on your Cloudways server.  The site is called aioseop-1297 and the URL is http://wordpress-118694-629969.cloudwaysapps.com/.

You can find example forum, topic and reply here:
view-source:http://wordpress-118694-629969.cloudwaysapps.com/forums/forum/test-forum/
view-source:http://wordpress-118694-629969.cloudwaysapps.com/forums/topic/test-topic/
view-source:http://wordpress-118694-629969.cloudwaysapps.com/forums/reply/15/

Let me know if you need me to send you WP admin login and SFTP.

**Comment by contactashish13** [comment]
@wpsmort can you send me the credentials on slack?

**Comment by wpsmort** [comment]
This is tested and is good.  Ready for code review.

**Pull request merged**
