### PR TITLE
Filter for controlling which description to use for WooCommerce products

### PR DESCRIPTION
**Pull request by contactashish13**
https://github.com/semperfiwebdesign/aioseop-pro/issues/185

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@contactashish13 

Returning false is just going to result in no description. 
If I'm understanding the issue correctly, this is supposed a) use the excerpt for the description and b) do it for WooCommerce.

**Comment by contactashish13** [comment]
@michaeltorbert returning false will NOT generate description from content but will retain the description that has already been generated from the excerpt.

**Comment by wpsmort** [comment]
@contactashish13 I couldn't get your example filters to work here https://github.com/semperfiwebdesign/aioseop-pro/issues/185#issuecomment-422692369.  I got this notice:

PHP Notice:  Undefined variable: post in /wp-content/themes/twentyseventeen/functions.php on line 617

**Comment by wpsmort** [comment]
@contactashish13 Please provide an example of how to use the filters here - https://github.com/semperfiwebdesign/aioseop-pro/issues/185#issuecomment-422692369

**Comment by contactashish13** [comment]
@wpsmort provided as part of the issue https://github.com/semperfiwebdesign/aioseop-pro/issues/185#issuecomment-430487296

**Comment by wpsmort** [comment]
@contactashish13 I tested using the example code that you provided and got this fatal error when Use Content For Autogenerated Descriptions is checked:

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function aiosp_generate_descriptions_from_content(), 1 passed in //wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in /wp-content/themes/twentyseventeen/functions.php:617

Also, the filter needs to work for a specific post type not a specific post.  So we need to be able to specify that for post type Product use the short description.  

Let me know if you have questions about this.

**Comment by wpsmort** [comment]
@michaeltorbert Can you take a look at the merge conflicts here please.  It seems to indicate that the entire file is causing the conflict.

**Comment by wpsmort** [comment]
I've tested with the code below with both posts and WooCommerce products and cannot get this to work, the excerpt is always output.  I'm testing with the current version of Pro:

```
add_filter( 'aiosp_generate_descriptions_from_content', 'aiosp_generate_descriptions_from_content', 10, 2 );

function aiosp_generate_descriptions_from_content( $return, $post ) {
    return $post->post_type  === 'post';
}

add_filter( 'aiosp_opengraph_generate_descriptions_from_content', 'aiosp_opengraph_generate_descriptions_from_content' );

function aiosp_opengraph_generate_descriptions_from_content( $return, $post, 10, 2 ) {
    return $post->post_type  === 'post';
}
```

**Comment by michaeltorbert** [comment]
@wpsmort Did you fix the code error?
I assume 10, 2 should be in the add_filter, not as the function's parameters.

**Comment by michaeltorbert** [comment]
What I'm not sure about is the condition that tests for !AIOSEOPPRO || ( AIOSEOPPRO && autogeneratedescriptions )

That doesn't make any sense to me.

**Comment by wpsmort** [comment]
@michaeltorbert I tested again with the changes as per your comment.  I was still unable to get this to work.  I tested with free and Pro.  

I tested with a new site with WooCommerce.  I tested with Autogenerate Descriptions enabled and Use Content for Autogenerated Descriptions disabled because the filter should use the content for products.  The description that was output was the short description and not the content.  

Here's the filter code:

```
add_filter( 'aiosp_generate_descriptions_from_content', 'aiosp_generate_descriptions_from_content', 10, 2 );

function aiosp_generate_descriptions_from_content( $return, $post ) {
    return $post->post_type  === 'product';
}

add_filter( 'aiosp_opengraph_generate_descriptions_from_content', 'aiosp_opengraph_generate_descriptions_from_content', 10, 2 );

function aiosp_opengraph_generate_descriptions_from_content( $return, $post ) {
    return $post->post_type  === 'product';
}
```

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by EkoJR** [comment]
I noticed the changes could be cleaned up a bit more, and I reduced the multiple function calls. The changes shouldn't affect the result, but I'll add needs testing just to confirm it's safe.

**Comment by wpsmort** [comment]
I tested again to ensure the changes made by Ben did not affect the behavior.  This is good to go.

**Pull request merged**
