### PR TITLE
Change grunt & coding standards

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2472

## Proposed changes

Improves Grunt & phpcs, and code corrections. Some rules were added TODO to prevent breaking changes.

## Types of changes

What types of changes does your code introduce?

- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.

## Testing instructions
None, just code improvements.

### CODE REVIEW

**Comment by michaeltorbert** [comment]
I'm moving this to 3.2 since it makes changes to every file.

**Comment by EkoJR** [comment]
ok, the more this gets pushed back, the more conflicts there is going to be, and the more difficult it becomes.

**Comment by michaeltorbert** [comment]
@EkoJR It's fine for now, it just couldn't go into 3.1 that we were rushing to get out as an emergency release.

**Comment by michaeltorbert** [comment]
@wpsmort Can you do full testing on this PR?

**Comment by wpsmort** [comment]
This has been thoroughly tested and is good.

**Pull request merged**
