### PR TITLE
XML Sitemap - Don't include content from trashed pages

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by michaeltorbert** [comment]
https://scrutinizer-ci.com/g/semperfiwebdesign/all-in-one-seo-pack/inspections/b4b8ad3c-55e9-400f-87ef-5324767b5498/code-structure/operation/%2Bglobal%5CAll_in_One_SEO_Pack_Sitemap%3A%3Aget_prio_from_posts

**Comment by contactashish13** [comment]
@michaeltorbert done

**Comment by wpsmort** [comment]
This is tested and is good to go.

**Comment by wpsmort** [comment]
@contactashish13 Please resolve the merge conflict.

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is ready for code review.

**Pull request merged**
