### PR TITLE
Fix PHP 7.3 warning

### LINKED ISSUE #2129: Warning: “continue” targeting switch is equivalent to “break”
Reported here: https://wordpress.org/support/topic/warning-continue-targeting-switch-is-equivalent-to-break-3/

> Warning: “continue” targeting switch is equivalent to “break”. Did you mean to use “continue 2”? in /data01/virt71886/domeenid/www.xyz.ee/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_opengraph.php on line 853

### PR DESCRIPTION
**Pull request by rebeccahum**
## Proposed changes

Fixes #2129.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Unit tests pass with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by GoyWebdesign** [comment]
Updated this morning with 2.11
Still having:
" Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/clients/5e3f9380bdb17ae95614148ff1af924e/myfunmusicschool/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_opengraph.php on line 971"

**Comment by fruscio64** [comment]
> Updated this morning with 2.11
> Still having:
> " Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/clients/5e3f9380bdb17ae95614148ff1af924e/myfunmusicschool/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_opengraph.php on line 971"

me too. how to fix it? thank you.

**Comment by arnaudbroes** [comment]
@rebeccahum @GoyWebdesign @fruscio64 which WordPress versions are you using? If you're using 4.9.8, please let me know if updating to a later version resolves the issue. This seems to be a known bug in WordPress 4.9.8, and I wasn't able to reproduce this on a test site running WordPress 5.0.3 on a web server with PHP 7.3.

**Comment by GoyWebdesign** [comment]
WordPress 5.0.3
PHP 7.3
I had the same problem with SiteOrigin pageBuilder, but it's sorted now.
Want more specific details about PHP version?

**Comment by arnaudbroes** [comment]
@GoyWebdesign any details you can share with me would be helpful.

**Comment by GoyWebdesign** [comment]
PHP Version 7.3.1

PHP API | 20180731
-- | --
PHP Extension | 20180731

**Comment by arnaudbroes** [comment]
@GoyWebdesign thank you for the information, I was now able to reproduce the issue. 
@michaeltorbert this has been tested. The PR fixes the issue and can be code reviewed.

**Comment by GoyWebdesign** [comment]
@arnaudbroes thank you for your time.

**Comment by fruscio64** [comment]
@arnaudbroes 
thank you. 

WordPress 5.0.3
PHP 7.3

**Comment by EkoJR** [comment]
This looks good, and ready for merge.

**Comment by GoyWebdesign** [comment]
Thank you

**Comment by rebeccahum** [comment]
@michaeltorbert Can we get this merged into the Pro version?  If it already has been, do you have a version number available with the compatibility changes?

**Comment by michaeltorbert** [comment]
@rebeccahum This has already been merged and is in the current version of Pro, which is 2.13.

**Pull request merged**
