### PR TITLE
Problem in XML sitemap caused by rsquo; character

### PR DESCRIPTION
**Pull request by contactashish13**
#2177

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@contactashish13 FYI, it's best to name your commits after what they actually do or fix instead of the name of the issue because "problem in XML sitemap" doesn't really tell us much.

**Comment by contactashish13** [comment]
In that case I think the name of the issue should change to "problem in sitemap because of rsqo character" because the commit addresses that. If there were multiple commits, subsequent commits do mention what changes from the first one.

**Comment by arnaudbroes** [comment]
@contactashish13 you definitely have a point there. If you think an issue could be described better with a different title and anyone else hasn't changed it already, then please feel free to edit it. :-)

**Comment by wpsmort** [comment]
This is tested and is good.  I was able to reproduce the original bug report and verify that this PR fixes it.

**Comment by EkoJR** [comment]
@contactashish13 If you'd like to improve the PHPUnit test, I found a list of Named Entities. https://gist.github.com/EkoJR/7caa0b4664be2ff1d6f508c8b4b362c9

**Pull request merged**
