### PR TITLE
Fix noindex & nofollow both required to operate

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #1957

### CODE REVIEW

**Comment by wpsmort** [comment]
@EkoJR I tested this and although it does add back the noindex and nofollow meta tags, it also incorrectly adds back the SEO and Open Graph meta tags as well.  I tested this with Posts and with a  Custom Post Type.  

Can you make sure that only the noindex and nofollow meta tags are displayed and all other SEO and OG meta is removed.

**Comment by EkoJR** [comment]
@wpsmort Programmatically, it doesn't seem it will be an easy change. The head function relies on a check to carry out the rest of the operation, which also relies on "SEO on only these post types". However, noindex and nofollow was still needed even if "SEO on only these post types" is unchecked. https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1797#issue-342578925

I think I'll have to change the concept in `\All_in_One_SEO_Pack::wp_head` to still print some data before the boolean check; which I was trying to avoid big changes. I think the only option is to migrate the changes to `\All_in_One_SEO_Pack::wp_head` as well as the rest of the Meta Robot code.

**Comment by wpsmort** [comment]
@EkoJR I tested that and it works fine when you uncheck the box for the post type under Custom Post Type Settings >  SEO on only these post types.  However, if you then select Disabled in the SEO for Custom Post Types option then the SEO meta is added back.

To reproduce, follow these steps:

1. Go to Custom Post Type Settings >  SEO on only these post types and uncheck Posts.
2. View the source code of any post and there should be no SEO meta, only the noindex and nofollow tags should be present.
3. Go to Custom Post Type Settings >  SEO for Custom Post Types and select Disabled.
4. View the source code of your post and the SEO meta should be back.

**Comment by EkoJR** [comment]
@wpsmort It looks like that is a seperate bug. 

The PHP code that exits the wp_head, checks `if ( empty( $aioseop_options['aiosp_enablecpost'] ) )`, but doesn't return a false boolean. It seems that is it still required to have the 'SEO on only these post types' setting.

This would be the code in question in `\All_in_One_SEO_Pack::is_page_included`
```
if ( empty( $aioseop_options['aiosp_enablecpost'] ) ) {
	$wp_post_types = get_post_types( array( '_builtin' => true ) ); // Don't display meta if SEO isn't enabled on custom post types -- pdb.
	if ( is_singular() && ! in_array( $post_type, $wp_post_types ) && ! is_front_page() ) {
		return false;
	}
}
```

**Comment by EkoJR** [comment]
It also seems SEO is added to builtin post types by default when disabled.

**Comment by EkoJR** [comment]
I also tested this with the last release (v2.8), and the effect is also a pre-existing.

**Comment by wpsmort** [comment]
@EkoJR Thanks for pointing that out.  In this case I don't think we want to fix that behavior because we intend to remove that option entirely - See #68.

I tested again with both Posts and a CPT.  Here are the results:

Testing with Posts:
- This works fine.  The noindex/nofollow meta tag is output correctly when you uncheck this post type in SEO on only these post types.

Testing with a CPT:
- This does not work.  The noindex/nofollow meta tag is output when you uncheck the post type in SEO on only these post types.

Can you fix this for custom post types please.

**Comment by wpsmort** [comment]
@EkoJR Thanks for pointing that out.  

This only affects the built-in post types not CPTs.  Given that we plan to remove that option (issue #68) and it's a preexisting bug, we should not fix it under this PR.  We should clean up that code when we remove the option.

I tested with built-in post types and with CPTs and this works correctly.   

This is now ready for code review.

**Pull request merged**
