### PR TITLE
Add option to disable animations or make transition better

### PR DESCRIPTION
**Pull request by contactashish13**
#1715

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@wpsmort perhaps assign this and probably all other similar issues to me after you're done testing for Windows browser testing.

**Comment by wpsmort** [comment]
@contactashish13 I tested this in Chrome, Firefox and Safari on Mac and found that the slow fade works when switching from the Main Settings tab to the Social Settings tab but it does not work when switching back to the Main Settings tab.

**Comment by michaeltorbert** [comment]
@arnaudbroes If multiple issues have overlapping code changes we're just going to double, triple, or more our efforts due to merge conflicts.
Let's try to get PRs completed as quickly as possible.

**Comment by contactashish13** [comment]
I think this PR no longer makes sense if https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2274 is implemented. Let me know how to proceed.

**Comment by michaeltorbert** [comment]
Are the transitions in #2274 improved for motion sickness?

**Pull request closed without merging**
