### PR TITLE
If a post/page is in Draft, an attachment id query string is generated to the sitemap even if the image is attached

### PR DESCRIPTION
**Pull request by contactashish13**
#1835

### CODE REVIEW

**Comment by wpsmort** [comment]
@michaeltorbert Please can you take a look at the two merge conflicts here.  There's also a Travis failed check.

**Comment by michaeltorbert** [comment]
@wpsmort Done.

**Comment by wpsmort** [comment]
@michaeltorbert I tested this and got this PHP Notice:

Undefined variable: _draft_posts_attachment_ids in modules/aioseop_sitemap.php on line 3968

**Comment by michaeltorbert** [comment]
$_draft_posts_attachment_ids doesn't exist. Looks like maybe @contactashish13 meant to do something with it and forgot but I don't know.
I'm closing this PR for now.

**Pull request closed without merging**
